----------------------------
-- NAT Pack1 Adapt by xhh --
----------------------------

--------------
-- Projects --
--------------
insert or ignore into Types
	(Type,												Kind)
values
	('PROJECT_CREATE_PRODUCT_AIRPORT_FOOD',				'KIND_PROJECT'),
	('RESOURCE_AIRPORT_FOOD',							'KIND_RESOURCE'),
	('PROJECT_CREATE_PRODUCT_AIRPORT_DRINK',			'KIND_PROJECT'),
	('RESOURCE_AIRPORT_DRINK',							'KIND_RESOURCE'),
	('PROJECT_CREATE_PRODUCT_AIRPORT_USING',			'KIND_PROJECT'),
	('RESOURCE_AIRPORT_USING',							'KIND_RESOURCE'),
	('BUILDING_INTERNATIONAL_AIRPORT_DUMMY',			'KIND_BUILDING');

insert or replace into Buildings 
    (BuildingType,          					Name,                           					Cost,   Description) 
values
    ('BUILDING_INTERNATIONAL_AIRPORT_DUMMY', 	'LOC_BUILDING_INTERNATIONAL_AIRPORT_DUMMY_NAME', 	1,    	'LOC_BUILDING_INTERNATIONAL_AIRPORT_DUMMY_DESCRIPTION');
insert or replace into Buildings_XP2 (BuildingType,Pillage) values ('BUILDING_INTERNATIONAL_AIRPORT_DUMMY',0);

insert or replace into HD_DUMMY_BUILDINGS (BuildingType) values ('BUILDING_INTERNATIONAL_AIRPORT_DUMMY');

insert or replace into BuildingModifiers
    (BuildingType,                  ModifierId)
values
    ('NAT_WON_CL_AIRPORT',          'HD_GRANT_BUILDING_INTERNATIONAL_AIRPORT_DUMMY');

insert or replace into Modifiers
    (ModifierId,                        				ModifierType,                                           	SubjectRequirementSetId)
values
    ('HD_GRANT_BUILDING_INTERNATIONAL_AIRPORT_DUMMY',   'MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE',   	'HD_CITY_HAS_NAT_AIRPORTS');

insert or replace into ModifierArguments
    (ModifierId,                        				Name,                Value)
values
	('HD_GRANT_BUILDING_INTERNATIONAL_AIRPORT_DUMMY',   'BuildingType',      'BUILDING_INTERNATIONAL_AIRPORT_DUMMY');

insert or ignore into Requirements
    (RequirementId,                             RequirementType)
values
    ('HD_REQUIRES_CITY_HAS_AIRPORT',            'REQUIREMENT_CITY_HAS_BUILDING'),
    ('HD_REQUIRES_CITY_HAS_NAT_AIRPORT',        'REQUIREMENT_CITY_HAS_BUILDING');

insert or ignore into RequirementArguments
    (RequirementId,                             Name,                Value)
values
    ('HD_REQUIRES_CITY_HAS_AIRPORT',            'BuildingType',		 'BUILDING_AIRPORT'),
    ('HD_REQUIRES_CITY_HAS_NAT_AIRPORT',        'BuildingType',		 'NAT_WON_CL_AIRPORT');

insert or ignore into RequirementSets
    (RequirementSetId,                          RequirementSetType)
values
    ('HD_CITY_HAS_NAT_AIRPORTS',		        'REQUIREMENTSET_TEST_ANY');

insert or ignore into RequirementSetRequirements
    (RequirementSetId,                          RequirementId)
values
    ('HD_CITY_HAS_NAT_AIRPORTS',		        'HD_REQUIRES_CITY_HAS_AIRPORT'),
    ('HD_CITY_HAS_NAT_AIRPORTS',		        'HD_REQUIRES_CITY_HAS_NAT_AIRPORT');
-----------------------

insert or replace into Resources
	(ResourceType,				Name,									ResourceClassType)
values
	('RESOURCE_AIRPORT_FOOD',	'LOC_RESOURCE_AIRPORT_FOOD_NAME',		'RESOURCECLASS_LUXURY'),
	('RESOURCE_AIRPORT_DRINK',	'LOC_RESOURCE_AIRPORT_DRINK_NAME',		'RESOURCECLASS_LUXURY'),
	('RESOURCE_AIRPORT_USING',	'LOC_RESOURCE_AIRPORT_USING_NAME',		'RESOURCECLASS_LUXURY');

insert or ignore into CivilopediaPageExcludes (SectionId, PageId)
	values ('RESOURCES', 'RESOURCE_AIRPORT_FOOD'),('RESOURCES', 'RESOURCE_AIRPORT_DRINK'),('RESOURCES', 'RESOURCE_AIRPORT_USING');

insert or replace into Projects
	(ProjectType,Name,ShortName,Description,Cost,AdvisorType,MaxPlayerInstances)
values
	(
	'PROJECT_CREATE_PRODUCT_AIRPORT_FOOD', 
	'LOC_PROJECT_CREATE_PRODUCT_AIRPORT_FOOD_NAME',
	'LOC_PROJECT_CREATE_PRODUCT_AIRPORT_FOOD_SHORT_NAME',
	'LOC_PROJECT_CREATE_PRODUCT_AIRPORT_FOOD_DESCRIPTION',
	250,
	'ADVISOR_GENERIC',
	19
	),
	(
	'PROJECT_CREATE_PRODUCT_AIRPORT_DRINK', 
	'LOC_PROJECT_CREATE_PRODUCT_AIRPORT_DRINK_NAME',
	'LOC_PROJECT_CREATE_PRODUCT_AIRPORT_DRINK_SHORT_NAME',
	'LOC_PROJECT_CREATE_PRODUCT_AIRPORT_DRINK_DESCRIPTION',
	250,
	'ADVISOR_GENERIC',
	15
	),
	(
	'PROJECT_CREATE_PRODUCT_AIRPORT_USING', 
	'LOC_PROJECT_CREATE_PRODUCT_AIRPORT_USING_NAME',
	'LOC_PROJECT_CREATE_PRODUCT_AIRPORT_USING_SHORT_NAME',
	'LOC_PROJECT_CREATE_PRODUCT_AIRPORT_USING_DESCRIPTION',
	250,
	'ADVISOR_GENERIC',
	16
	);

insert or ignore into Projects_XP2 (ProjectType, RequiredBuilding) values
	('PROJECT_CREATE_PRODUCT_AIRPORT_FOOD', 'BUILDING_INTERNATIONAL_AIRPORT_DUMMY'),
	('PROJECT_CREATE_PRODUCT_AIRPORT_DRINK', 'BUILDING_INTERNATIONAL_AIRPORT_DUMMY'),
	('PROJECT_CREATE_PRODUCT_AIRPORT_USING', 'BUILDING_INTERNATIONAL_AIRPORT_DUMMY');

insert or replace into ProjectCompletionModifiers
	(ProjectType,								ModifierId)
values
	('PROJECT_CREATE_PRODUCT_AIRPORT_FOOD',		'PROJECT_COMPLETE_CREATE_AIRPORT_FOOD_PRODUCT'),
	('PROJECT_CREATE_PRODUCT_AIRPORT_DRINK',	'PROJECT_COMPLETE_CREATE_AIRPORT_DRINK_PRODUCT'),
	('PROJECT_CREATE_PRODUCT_AIRPORT_USING',	'PROJECT_COMPLETE_CREATE_AIRPORT_USING_PRODUCT');

insert or replace into Modifiers
	(ModifierId,											ModifierType)
values
	('PROJECT_COMPLETE_CREATE_AIRPORT_FOOD_PRODUCT',		'MODIFIER_PLAYER_GRANT_RANDOM_RESOURCE_PRODUCT'),
	('PROJECT_COMPLETE_CREATE_AIRPORT_DRINK_PRODUCT',		'MODIFIER_PLAYER_GRANT_RANDOM_RESOURCE_PRODUCT'),
	('PROJECT_COMPLETE_CREATE_AIRPORT_USING_PRODUCT',		'MODIFIER_PLAYER_GRANT_RANDOM_RESOURCE_PRODUCT');

insert or replace into ModifierArguments
	(ModifierId,											Name,			Value)
values
	('PROJECT_COMPLETE_CREATE_AIRPORT_FOOD_PRODUCT',		'ResourceType',	'RESOURCE_AIRPORT_FOOD'),
	('PROJECT_COMPLETE_CREATE_AIRPORT_DRINK_PRODUCT',		'ResourceType',	'RESOURCE_AIRPORT_DRINK'),
	('PROJECT_COMPLETE_CREATE_AIRPORT_USING_PRODUCT',		'ResourceType',	'RESOURCE_AIRPORT_USING');

--------------
-- Products --
--------------
CREATE TEMPORARY TABLE "HD_AIRPORT_FOOD_Products"(
    'Num'  TEXT
);
insert or replace into HD_AIRPORT_FOOD_Products (Num) values
	('1'),('2'),('3'),('4'),('5'),('6'),('7'),('8'),('9'),('A'),('B'),('C'),('D'),('E'),('F'),('G'),('H'),('I'),('J');

insert or replace into Types
	(Type,										Kind)
select
	'GREATWORK_PRODUCT_AIRPORT_FOOD_'|| Num, 	'KIND_GREATWORK'
from HD_AIRPORT_FOOD_Products;

insert or replace into GreatWorks
	(GreatWorkType,								GreatWorkObjectType,			Tourism,	Name)
select
	'GREATWORK_PRODUCT_AIRPORT_FOOD_'|| Num, 	'GREATWORKOBJECT_PRODUCT',	12,			'LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_'|| Num || '_NAME'
from HD_AIRPORT_FOOD_Products;

insert or replace into GreatWorks_ImprovementType
	(GreatWorkType,								ResourceType)
select
	'GREATWORK_PRODUCT_AIRPORT_FOOD_'|| Num,	'RESOURCE_AIRPORT_FOOD'
from HD_AIRPORT_FOOD_Products;

--------------------------------

CREATE TEMPORARY TABLE "HD_AIRPORT_DRINK_Products"(
    'Num'  TEXT
);
insert or replace into HD_AIRPORT_DRINK_Products (Num) values
	('1'),('2'),('3'),('4'),('5'),('6'),('7'),('8'),('9'),('A'),('B'),('C'),('D'),('E'),('F');

insert or replace into Types
	(Type,										Kind)
select
	'GREATWORK_PRODUCT_AIRPORT_DRINK_'|| Num, 	'KIND_GREATWORK'
from HD_AIRPORT_DRINK_Products;

insert or replace into GreatWorks
	(GreatWorkType,								GreatWorkObjectType,		Tourism,	Name)
select
	'GREATWORK_PRODUCT_AIRPORT_DRINK_'|| Num, 	'GREATWORKOBJECT_PRODUCT',	12,			'LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_'|| Num || '_NAME'
from HD_AIRPORT_DRINK_Products;

insert or replace into GreatWorks_ImprovementType
	(GreatWorkType,								ResourceType)
select
	'GREATWORK_PRODUCT_AIRPORT_DRINK_'|| Num,	'RESOURCE_AIRPORT_DRINK'
from HD_AIRPORT_DRINK_Products;

--------------------------------

CREATE TEMPORARY TABLE "HD_AIRPORT_USING_Products"(
    'Num'  TEXT
);
insert or replace into HD_AIRPORT_USING_Products (Num) values
	('1'),('2'),('3'),('4'),('5'),('6'),('7'),('8'),('9'),('A'),('B'),('C'),('D'),('E'),('F'),('G');

insert or replace into Types
	(Type,										Kind)
select
	'GREATWORK_PRODUCT_AIRPORT_USING_'|| Num, 	'KIND_GREATWORK'
from HD_AIRPORT_USING_Products;

insert or replace into GreatWorks
	(GreatWorkType,								GreatWorkObjectType,		Tourism,	Name)
select
	'GREATWORK_PRODUCT_AIRPORT_USING_'|| Num, 	'GREATWORKOBJECT_PRODUCT',	12,			'LOC_GREATWORK_PRODUCT_AIRPORT_USING_'|| Num || '_NAME'
from HD_AIRPORT_USING_Products;

insert or replace into GreatWorks_ImprovementType
	(GreatWorkType,								ResourceType)
select
	'GREATWORK_PRODUCT_AIRPORT_USING_'|| Num,	'RESOURCE_AIRPORT_USING'
from HD_AIRPORT_USING_Products;

--------------------------------

insert or replace into GreatWork_YieldChanges
    (GreatWorkType,                     	YieldType,          YieldChange)
values
	('GREATWORK_PRODUCT_AIRPORT_DRINK_1',	'YIELD_FOOD',		9),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_1',	'YIELD_GOLD',		2),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_2',	'YIELD_SCIENCE',	6),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_2',	'YIELD_CULTURE',	4),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_3',	'YIELD_CULTURE',	5),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_3',	'YIELD_FAITH',		5),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_4',	'YIELD_FOOD',		2),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_4',	'YIELD_CULTURE',	4),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_4',	'YIELD_GOLD',		8),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_5',	'YIELD_SCIENCE',	4),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_5',	'YIELD_CULTURE',	6),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_6',	'YIELD_PRODUCTION',	4),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_6',	'YIELD_GOLD',		12),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_7',	'YIELD_CULTURE',	3),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_7',	'YIELD_FAITH',		7),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_8',	'YIELD_FOOD',		3),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_8',	'YIELD_CULTURE',	7),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_9',	'YIELD_FOOD',		3),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_9',	'YIELD_GOLD',		14),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_A',	'YIELD_FOOD',		3),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_A',	'YIELD_FAITH',		1),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_A',	'YIELD_GOLD',		12),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_B',	'YIELD_FOOD',		2),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_B',	'YIELD_CULTURE',	4),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_B',	'YIELD_GOLD',		8),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_C',	'YIELD_FOOD',		1),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_C',	'YIELD_SCIENCE',	9),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_D',	'YIELD_FOOD',		1),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_D',	'YIELD_CULTURE',	6),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_D',	'YIELD_GOLD',		6),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_E',	'YIELD_FOOD',		1),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_E',	'YIELD_CULTURE',	4),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_E',	'YIELD_GOLD',		10),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_F',	'YIELD_FOOD',		1),
	('GREATWORK_PRODUCT_AIRPORT_DRINK_F',	'YIELD_GOLD',		18),

	('GREATWORK_PRODUCT_AIRPORT_FOOD_1',	'YIELD_FOOD',		9),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_1',	'YIELD_CULTURE',	1),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_2',	'YIELD_FOOD',		9),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_2',	'YIELD_FAITH',		1),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_3',	'YIELD_FOOD',		8),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_3',	'YIELD_GOLD',		4),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_4',	'YIELD_FOOD',		8),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_4',	'YIELD_PRODUCTION',	1),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_4',	'YIELD_GOLD',		2),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_5',	'YIELD_FOOD',		8),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_5',	'YIELD_FAITH',		2),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_6',	'YIELD_FOOD',		7),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_6',	'YIELD_GOLD',		6),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_7',	'YIELD_FOOD',		6),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_7',	'YIELD_GOLD',		8),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_8',	'YIELD_FOOD',		6),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_8',	'YIELD_FAITH',		4),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_9',	'YIELD_FOOD',		6),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_9',	'YIELD_PRODUCTION',	4),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_A',	'YIELD_FOOD',		6),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_A',	'YIELD_PRODUCTION',	1),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_A',	'YIELD_GOLD',		6),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_B',	'YIELD_FOOD',		5),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_B',	'YIELD_CULTURE',	5),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_C',	'YIELD_FOOD',		5),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_C',	'YIELD_CULTURE',	2),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_C',	'YIELD_GOLD',		6),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_D',	'YIELD_FOOD',		5),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_D',	'YIELD_PRODUCTION',	2),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_D',	'YIELD_GOLD',		6),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_E',	'YIELD_FOOD',		5),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_E',	'YIELD_GOLD',		10),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_F',	'YIELD_FOOD',		3),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_F',	'YIELD_PRODUCTION',	7),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_G',	'YIELD_FOOD',		3),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_G',	'YIELD_PRODUCTION',	3),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_G',	'YIELD_CULTURE',	4),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_H',	'YIELD_FOOD',		2),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_H',	'YIELD_SCIENCE',	8),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_I',	'YIELD_FOOD',		1),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_I',	'YIELD_SCIENCE',	5),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_I',	'YIELD_FAITH',		4),
	('GREATWORK_PRODUCT_AIRPORT_FOOD_J',	'YIELD_FOOD',		10),

	('GREATWORK_PRODUCT_AIRPORT_USING_1',	'YIELD_PRODUCTION',	8),
	('GREATWORK_PRODUCT_AIRPORT_USING_1',	'YIELD_FAITH',		2),
	('GREATWORK_PRODUCT_AIRPORT_USING_2',	'YIELD_CULTURE',	7),
	('GREATWORK_PRODUCT_AIRPORT_USING_2',	'YIELD_GOLD',		6),
	('GREATWORK_PRODUCT_AIRPORT_USING_3',	'YIELD_PRODUCTION',	7),
	('GREATWORK_PRODUCT_AIRPORT_USING_3',	'YIELD_CULTURE',	3),
	('GREATWORK_PRODUCT_AIRPORT_USING_4',	'YIELD_PRODUCTION',	7),
	('GREATWORK_PRODUCT_AIRPORT_USING_4',	'YIELD_SCIENCE',	3),
	('GREATWORK_PRODUCT_AIRPORT_USING_5',	'YIELD_CULTURE',	6),
	('GREATWORK_PRODUCT_AIRPORT_USING_5',	'YIELD_GOLD',		8),
	('GREATWORK_PRODUCT_AIRPORT_USING_6',	'YIELD_CULTURE',	6),
	('GREATWORK_PRODUCT_AIRPORT_USING_6',	'YIELD_FAITH',		4),
	('GREATWORK_PRODUCT_AIRPORT_USING_7',	'YIELD_SCIENCE',	5),
	('GREATWORK_PRODUCT_AIRPORT_USING_7',	'YIELD_FAITH',		5),
	('GREATWORK_PRODUCT_AIRPORT_USING_8',	'YIELD_CULTURE',	4),
	('GREATWORK_PRODUCT_AIRPORT_USING_8',	'YIELD_FAITH',		6),
	('GREATWORK_PRODUCT_AIRPORT_USING_9',	'YIELD_PRODUCTION',	2),
	('GREATWORK_PRODUCT_AIRPORT_USING_9',	'YIELD_CULTURE',	4),
	('GREATWORK_PRODUCT_AIRPORT_USING_9',	'YIELD_GOLD',		8),
	('GREATWORK_PRODUCT_AIRPORT_USING_A',	'YIELD_PRODUCTION',	4),
	('GREATWORK_PRODUCT_AIRPORT_USING_A',	'YIELD_SCIENCE',	4),
	('GREATWORK_PRODUCT_AIRPORT_USING_A',	'YIELD_GOLD',		4),
	('GREATWORK_PRODUCT_AIRPORT_USING_B',	'YIELD_GOLD',		20),
	('GREATWORK_PRODUCT_AIRPORT_USING_C',	'YIELD_PRODUCTION',	1),
	('GREATWORK_PRODUCT_AIRPORT_USING_C',	'YIELD_GOLD',		18),
	('GREATWORK_PRODUCT_AIRPORT_USING_D',	'YIELD_CULTURE',	10),
	('GREATWORK_PRODUCT_AIRPORT_USING_E',	'YIELD_SCIENCE',	10),
	('GREATWORK_PRODUCT_AIRPORT_USING_F',	'YIELD_FAITH',		10),
	('GREATWORK_PRODUCT_AIRPORT_USING_G',	'YIELD_PRODUCTION',	10);

-------------
-- Theming --
-------------
insert or replace into HD_Monopoly_Categories (Category) values ('AIRPORT_FOOD'),('AIRPORT_DRINK'),('AIRPORT_USING');
insert or replace into HDMonopolyResourceEffects (ResourceType,Category,IndustryEffect,CorporationEffect)
	values 
('RESOURCE_AIRPORT_FOOD','AIRPORT_FOOD','INDUSTRY_HD_AIRPORT_FOOD_BONUS','CORPORATION_HD_AIRPORT_FOOD_BONUS'),
('RESOURCE_AIRPORT_DRINK','AIRPORT_DRINK','INDUSTRY_HD_AIRPORT_DRINK_BONUS','CORPORATION_HD_AIRPORT_DRINK_BONUS'),
('RESOURCE_AIRPORT_USING','AIRPORT_USING','INDUSTRY_HD_AIRPORT_USING_BONUS','CORPORATION_HD_AIRPORT_USING_BONUS');