----------------------------
-- NAT Pack1 Adapt by xhh --
----------------------------

-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                               Text)
values
    ("LOC_HD_NAT_AIRPORT_CORP_ADD",                                     "Allows Cities having Airport districts or International Airport wonder to import [ICON_RESOURCE_AIRPORT_FOOD] Food Products, [ICON_RESOURCE_AIRPORT_DRINK] Drinking Products and [ICON_RESOURCE_AIRPORT_USING] Commodity Products from countries around the world."),
    ("LOC_BUILDING_INTERNATIONAL_AIRPORT_DUMMY_NAME",                   "Airport Import Licence"),
    ("LOC_BUILDING_INTERNATIONAL_AIRPORT_DUMMY_DESCRIPTION",            "Allows this city to import [ICON_RESOURCE_AIRPORT_FOOD] Food Products, [ICON_RESOURCE_AIRPORT_DRINK] Drinking Products and [ICON_RESOURCE_AIRPORT_USING] Commodity Products from countries around the world."),
    
    ("LOC_RESOURCE_AIRPORT_DRINK_NAME",                                     "[ICON_DISTRICT_WONDER] International Terminal [ICON_RESOURCE_AIRPORT_DRINK] Imported Drinking Product"),
    ("LOC_PROJECT_CREATE_PRODUCT_AIRPORT_DRINK_NAME",                       "[ICON_DISTRICT_WONDER] International Terminal: Import new [ICON_RESOURCE_AIRPORT_DRINK] Drinking Product"),
    ("LOC_PROJECT_CREATE_PRODUCT_AIRPORT_DRINK_SHORT_NAME",                 "[ICON_DISTRICT_WONDER] Import new [ICON_RESOURCE_AIRPORT_DRINK] Drinking Product from International Terminal"),
    ("LOC_PROJECT_CREATE_PRODUCT_AIRPORT_DRINK_DESCRIPTION",                "Allows import of [ICON_RESOURCE_AIRPORT_DRINK] Drinking Products (max. 15) when [ICON_DISTRICT_WONDER] International Terminal is built."),
    
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_1_NAME",                          "Maple Syrup"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_2_NAME",                          "Keemun Black Tea"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_3_NAME",                          "Airag"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_4_NAME",                          "Vinho Verde"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_5_NAME",                          "Colombian Coffee"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_6_NAME",                          "Mediterranean Olive Oil"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_7_NAME",                          "Paprikash"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_8_NAME",                          "Sharbat"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_9_NAME",                          "Buddha Jumps Over the Wall"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_A_NAME",                          "Chilli Honey Chocolate"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_B_NAME",                          "Weissbier"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_C_NAME",                          "Kikeliba Tea"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_D_NAME",                          "Macedonian Wine"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_E_NAME",                          "Lingonsylt"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_F_NAME",                          "Russian Vodka"),

    ("LOC_RESOURCE_AIRPORT_FOOD_NAME",                                     "[ICON_DISTRICT_WONDER] International Terminal [ICON_RESOURCE_AIRPORT_FOOD] Imported Food Product"),
    ("LOC_PROJECT_CREATE_PRODUCT_AIRPORT_FOOD_NAME",                       "[ICON_DISTRICT_WONDER] International Terminal: Import new [ICON_RESOURCE_AIRPORT_FOOD] Food Product"),
    ("LOC_PROJECT_CREATE_PRODUCT_AIRPORT_FOOD_SHORT_NAME",                 "[ICON_DISTRICT_WONDER] Import new [ICON_RESOURCE_AIRPORT_FOOD] Food Product from International Terminal"),
    ("LOC_PROJECT_CREATE_PRODUCT_AIRPORT_FOOD_DESCRIPTION",                "Allows import of [ICON_RESOURCE_AIRPORT_FOOD] Food Products (max. 19) when [ICON_DISTRICT_WONDER] International Terminal is built."),
    
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_1_NAME",                          "Yukpo"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_2_NAME",                          "Buffalo Robes"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_3_NAME",                          "Fufu"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_4_NAME",                          "Salted Hams"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_5_NAME",                          "Baguette"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_6_NAME",                          "Tamale"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_7_NAME",                          "Stroopwafels"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_8_NAME",                          "Churros"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_9_NAME",                          "Camel Liver"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_A_NAME",                          "M9 Australian Beef"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_B_NAME",                          "Pecorino Romano"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_C_NAME",                          "Injera Bread"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_D_NAME",                          "Fish & Chips"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_E_NAME",                          "Charquican"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_F_NAME",                          "Roast Cuy"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_G_NAME",                          "Churchkhela"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_H_NAME",                          "The Unwinding"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_I_NAME",                          "A-ping"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_J_NAME",                          "Oncom Spore Cakes"),

    ("LOC_RESOURCE_AIRPORT_USING_NAME",                                     "[ICON_DISTRICT_WONDER] International Terminal [ICON_RESOURCE_AIRPORT_USING] Imported Commodity Product"),
    ("LOC_PROJECT_CREATE_PRODUCT_AIRPORT_USING_NAME",                       "[ICON_DISTRICT_WONDER] International Terminal: Import new [ICON_RESOURCE_AIRPORT_USING] Commodity Product"),
    ("LOC_PROJECT_CREATE_PRODUCT_AIRPORT_USING_SHORT_NAME",                 "[ICON_DISTRICT_WONDER] Import new [ICON_RESOURCE_AIRPORT_USING] Commodity Product from International Terminal"),
    ("LOC_PROJECT_CREATE_PRODUCT_AIRPORT_USING_DESCRIPTION",                "Allows import of [ICON_RESOURCE_AIRPORT_USING] Commodity Products (max. 16) when [ICON_DISTRICT_WONDER] International Terminal is built."),
    
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_1_NAME",                          "Recurve Bow"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_2_NAME",                          "Samba Dress"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_3_NAME",                          "Model of Hippodrome"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_4_NAME",                          "Iklwa"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_5_NAME",                          "Scottish bagpipes"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_6_NAME",                          "Lyres"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_7_NAME",                          "Runestone"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_8_NAME",                          "Pisanki"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_9_NAME",                          "Pounamu"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_A_NAME",                          "Emeralds"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_B_NAME",                          "Persian Silverware"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_C_NAME",                          "Teddy Bear"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_D_NAME",                          "Sitar"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_E_NAME",                          "Senet Chess"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_F_NAME",                          "Yosegi-zukuri"),
    ("LOC_GREATWORK_PRODUCT_AIRPORT_USING_G_NAME",                          "Lebanon Cedar");


-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                               Text)
values
    ("zh_Hans_CN",  "LOC_HD_NAT_AIRPORT_CORP_ADD",                                     "建成后允许拥有机场（包括国际机场）的城市从世界各国进口具有文明特色的 [ICON_RESOURCE_AIRPORT_FOOD] 食品、 [ICON_RESOURCE_AIRPORT_DRINK] 饮料和 [ICON_RESOURCE_AIRPORT_USING] 工艺品。"),
    ("zh_Hans_CN",  "LOC_BUILDING_INTERNATIONAL_AIRPORT_DUMMY_NAME",                   "机场进口许可证"),
    ("zh_Hans_CN",  "LOC_BUILDING_INTERNATIONAL_AIRPORT_DUMMY_DESCRIPTION",            "建成奇观“国际机场”后，允许拥有机场（包括国际机场）城市从世界各国进口具有文明特色的 [ICON_RESOURCE_AIRPORT_FOOD] 食品、 [ICON_RESOURCE_AIRPORT_DRINK] 饮料和 [ICON_RESOURCE_AIRPORT_USING] 工艺品。"),
    
    ("zh_Hans_CN",  "LOC_RESOURCE_AIRPORT_DRINK_NAME",                                     "[ICON_DISTRICT_WONDER] 国际机场 [ICON_RESOURCE_AIRPORT_DRINK] 进口饮料"),
    ("zh_Hans_CN",  "LOC_PROJECT_CREATE_PRODUCT_AIRPORT_DRINK_NAME",                       "[ICON_DISTRICT_WONDER] 国际机场：进口新的 [ICON_RESOURCE_AIRPORT_DRINK] 饮料"),
    ("zh_Hans_CN",  "LOC_PROJECT_CREATE_PRODUCT_AIRPORT_DRINK_SHORT_NAME",                 "[ICON_DISTRICT_WONDER] 国际机场：进口新的 [ICON_RESOURCE_AIRPORT_DRINK] 饮料"),
    ("zh_Hans_CN",  "LOC_PROJECT_CREATE_PRODUCT_AIRPORT_DRINK_DESCRIPTION",                "完成 [ICON_DISTRICT_WONDER] 奇观“国际机场”后允许此城从世界各国进口 [ICON_RESOURCE_AIRPORT_DRINK] 饮料。最多可以进口15种 [ICON_RESOURCE_AIRPORT_DRINK] 饮料。"),

    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_1_NAME",                          "枫糖浆"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_2_NAME",                          "祁门红茶"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_3_NAME",                          "马奶酒"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_4_NAME",                          "葡萄牙青酒"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_5_NAME",                          "哥伦比亚咖啡"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_6_NAME",                          "地中海橄榄油"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_7_NAME",                          "匈牙利辣酱"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_8_NAME",                          "阿拉伯果子露"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_9_NAME",                          "佛跳墙"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_A_NAME",                          "辣椒蜂蜜巧克力"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_B_NAME",                          "德国白啤酒"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_C_NAME",                          "风车子茶叶"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_D_NAME",                          "马其顿葡萄酒"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_E_NAME",                          "越橘酱"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_DRINK_F_NAME",                          "俄罗斯伏特加"),

    ("zh_Hans_CN",  "LOC_RESOURCE_AIRPORT_FOOD_NAME",                                     "[ICON_DISTRICT_WONDER] 国际机场 [ICON_RESOURCE_AIRPORT_FOOD] 进口食品"),
    ("zh_Hans_CN",  "LOC_PROJECT_CREATE_PRODUCT_AIRPORT_FOOD_NAME",                       "[ICON_DISTRICT_WONDER] 国际机场：进口新的 [ICON_RESOURCE_AIRPORT_FOOD] 食品"),
    ("zh_Hans_CN",  "LOC_PROJECT_CREATE_PRODUCT_AIRPORT_FOOD_SHORT_NAME",                 "[ICON_DISTRICT_WONDER] 国际机场：进口新的 [ICON_RESOURCE_AIRPORT_FOOD] 食品"),
    ("zh_Hans_CN",  "LOC_PROJECT_CREATE_PRODUCT_AIRPORT_FOOD_DESCRIPTION",                "完成 [ICON_DISTRICT_WONDER] 奇观“国际机场”后允许此城从世界各国进口 [ICON_RESOURCE_AIRPORT_FOOD] 食品。最多可以进口19种 [ICON_RESOURCE_AIRPORT_FOOD] 食品。"),

    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_1_NAME",                          "酱牛肉"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_2_NAME",                          "印第安式干肉饼"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_3_NAME",                          "木薯泥"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_4_NAME",                          "盐腌火腿"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_5_NAME",                          "法棍"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_6_NAME",                          "墨西哥粽"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_7_NAME",                          "焦糖松饼"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_8_NAME",                          "西班牙小油条"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_9_NAME",                          "炒骆驼肝"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_A_NAME",                          "M9澳洲牛肉"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_B_NAME",                          "咸羊奶奶酪"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_C_NAME",                          "英吉拉面包"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_D_NAME",                          "炸鱼薯条"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_E_NAME",                          "查奎坎炖牛肉"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_F_NAME",                          "烤豚鼠"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_G_NAME",                          "丘尔其赫拉棒"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_H_NAME",                          "黯然销魂饭"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_I_NAME",                          "油炸毒蜘蛛"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_FOOD_J_NAME",                          "豆渣糕"),

    ("zh_Hans_CN",  "LOC_RESOURCE_AIRPORT_USING_NAME",                                     "[ICON_DISTRICT_WONDER] 国际机场 [ICON_RESOURCE_AIRPORT_USING] 进口工艺品"),
    ("zh_Hans_CN",  "LOC_PROJECT_CREATE_PRODUCT_AIRPORT_USING_NAME",                       "[ICON_DISTRICT_WONDER] 国际机场：进口新的 [ICON_RESOURCE_AIRPORT_USING] 工艺品"),
    ("zh_Hans_CN",  "LOC_PROJECT_CREATE_PRODUCT_AIRPORT_USING_SHORT_NAME",                 "[ICON_DISTRICT_WONDER] 国际机场：进口新的 [ICON_RESOURCE_AIRPORT_USING] 工艺品"),
    ("zh_Hans_CN",  "LOC_PROJECT_CREATE_PRODUCT_AIRPORT_USING_DESCRIPTION",                "完成 [ICON_DISTRICT_WONDER] 奇观“国际机场”后允许此城从世界各国进口 [ICON_RESOURCE_AIRPORT_USING] 工艺品。最多可以进口16种 [ICON_RESOURCE_AIRPORT_USING] 工艺品。"),

    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_1_NAME",                          "反曲弓"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_2_NAME",                          "桑巴舞裙"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_3_NAME",                          "拜占庭赛车模型"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_4_NAME",                          "伊可瓦矛"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_5_NAME",                          "苏格兰风笛"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_6_NAME",                          "七弦竖琴"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_7_NAME",                          "如尼符文石"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_8_NAME",                          "彩绘蛋"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_9_NAME",                          "普纳姆玉"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_A_NAME",                          "土耳其绿宝石"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_B_NAME",                          "波斯银器"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_C_NAME",                          "泰迪熊"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_D_NAME",                          "锡塔尔琴"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_E_NAME",                          "塞尼特棋"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_F_NAME",                          "寄木造佛像"),
    ("zh_Hans_CN",  "LOC_GREATWORK_PRODUCT_AIRPORT_USING_G_NAME",                          "黎巴嫩雪松");