-- 宗教社区
insert or ignore into BeliefModifiers (BeliefType, ModifierId) values
  ('BELIEF_RELIGIOUS_COMMUNITY', 'HD_RELIGIOUS_COMMUNITY_MONOPOLY_UNITS_PURCHASE'),
  ('BELIEF_RELIGIOUS_COMMUNITY', 'HD_RELIGIOUS_COMMUNITY_UNIT_LEU_TYCOON_DISCOUNT'),
  ('BELIEF_RELIGIOUS_COMMUNITY', 'HD_RELIGIOUS_COMMUNITY_UNIT_LEU_INVESTOR_DISCOUNT'),
  ('BELIEF_RELIGIOUS_COMMUNITY', 'HD_RELIGIOUS_COMMUNITY_UNIT_HD_OVERSEAS_INVESTOR_DISCOUNT');

insert or ignore into Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) values
  ('HD_RELIGIOUS_COMMUNITY_MONOPOLY_UNITS_PURCHASE',						          'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('HD_RELIGIOUS_COMMUNITY_MONOPOLY_UNITS_PURCHASE_MODIFIER',			        'MODIFIER_CITY_ENABLE_UNIT_FAITH_PURCHASE',         NULL),
  ('HD_RELIGIOUS_COMMUNITY_UNIT_LEU_TYCOON_DISCOUNT',						          'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('HD_RELIGIOUS_COMMUNITY_UNIT_LEU_TYCOON_DISCOUNT_MODIFIER',			      'MODIFIER_SINGLE_CITY_ADJUST_UNIT_PURCHASE_COST',   NULL),
  ('HD_RELIGIOUS_COMMUNITY_UNIT_LEU_INVESTOR_DISCOUNT',						        'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('HD_RELIGIOUS_COMMUNITY_UNIT_LEU_INVESTOR_DISCOUNT_MODIFIER',			    'MODIFIER_SINGLE_CITY_ADJUST_UNIT_PURCHASE_COST',   NULL),
  ('HD_RELIGIOUS_COMMUNITY_UNIT_HD_OVERSEAS_INVESTOR_DISCOUNT',           'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',							'CITY_FOLLOWS_RELIGION_REQUIREMENTS'),
	('HD_RELIGIOUS_COMMUNITY_UNIT_HD_OVERSEAS_INVESTOR_DISCOUNT_MODIFIER',  'MODIFIER_SINGLE_CITY_ADJUST_UNIT_PURCHASE_COST',   NULL);

insert or replace into ModifierArguments (ModifierId, Name, Value) values
  ('HD_RELIGIOUS_COMMUNITY_MONOPOLY_UNITS_PURCHASE',						          'ModifierId',   'HD_RELIGIOUS_COMMUNITY_MONOPOLY_UNITS_PURCHASE_MODIFIER'),
	('HD_RELIGIOUS_COMMUNITY_MONOPOLY_UNITS_PURCHASE_MODIFIER',			        'Tag',          'CLASS_MONOPOLY_UNIT'),
  ('HD_RELIGIOUS_COMMUNITY_UNIT_LEU_TYCOON_DISCOUNT',						          'ModifierId',   'HD_RELIGIOUS_COMMUNITY_UNIT_LEU_TYCOON_DISCOUNT_MODIFIER'),
	('HD_RELIGIOUS_COMMUNITY_UNIT_LEU_TYCOON_DISCOUNT_MODIFIER',			      'UnitType',     'UNIT_LEU_TYCOON'),
	('HD_RELIGIOUS_COMMUNITY_UNIT_LEU_TYCOON_DISCOUNT_MODIFIER',			      'Amount',				15),
  ('HD_RELIGIOUS_COMMUNITY_UNIT_LEU_INVESTOR_DISCOUNT',						        'ModifierId',   'HD_RELIGIOUS_COMMUNITY_UNIT_LEU_INVESTOR_DISCOUNT_MODIFIER'),
	('HD_RELIGIOUS_COMMUNITY_UNIT_LEU_INVESTOR_DISCOUNT_MODIFIER',			    'UnitType',     'UNIT_LEU_INVESTOR'),
	('HD_RELIGIOUS_COMMUNITY_UNIT_LEU_INVESTOR_DISCOUNT_MODIFIER',			    'Amount',				15),
  ('HD_RELIGIOUS_COMMUNITY_UNIT_HD_OVERSEAS_INVESTOR_DISCOUNT',           'ModifierId',   'HD_RELIGIOUS_COMMUNITY_UNIT_HD_OVERSEAS_INVESTOR_DISCOUNT_MODIFIER'),
	('HD_RELIGIOUS_COMMUNITY_UNIT_HD_OVERSEAS_INVESTOR_DISCOUNT_MODIFIER',  'UnitType',     'UNIT_HD_OVERSEAS_INVESTOR'),
	('HD_RELIGIOUS_COMMUNITY_UNIT_HD_OVERSEAS_INVESTOR_DISCOUNT_MODIFIER',  'Amount',				15);