
---------------------------------------------------------------------------------------------------------------------------------------------------------------
-- DynamicModifiers
---------------------------------------------------------------------------------------------------------------------------------------------------------------
insert or ignore into Types
	(Type,																		      													Kind)
values
	('MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',																'KIND_MODIFIER'),
	('MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',															'KIND_MODIFIER'),
  ('MODIFIER_PLAYER_UNITS_ADJUST_IGNORE_TERRAIN', 													'KIND_MODIFIER'),
	('MODIFIER_SINGLE_CITY_ADJUST_TRAIT_AMENITY',	  													'KIND_MODIFIER'),
	('MODIFIER_SINGLE_CITY_DISTRICT_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'KIND_MODIFIER'),
	('MODIFIER_SINGLE_CITY_ADJUST_PROPERTY',																	'KIND_MODIFIER');

insert or ignore into DynamicModifiers
	(ModifierType,																  													CollectionType,						        EffectType)
values
	('MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',																'COLLECTION_CITY_DISTRICTS',			'EFFECT_ATTACH_MODIFIER'),
	('MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',   													'COLLECTION_PLAYER_DISTRICTS', 		'EFFECT_ATTACH_MODIFIER'),
  ('MODIFIER_PLAYER_UNITS_ADJUST_IGNORE_TERRAIN', 													'COLLECTION_PLAYER_UNITS',        'EFFECT_ADJUST_UNIT_IGNORE_TERRAIN_COST'),
	('MODIFIER_SINGLE_CITY_ADJUST_TRAIT_AMENITY',	  													'COLLECTION_OWNER',			          'EFFECT_ADJUST_TRAIT_AMENITY'),
	('MODIFIER_SINGLE_CITY_DISTRICT_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'COLLECTION_CITY_DISTRICTS',			'EFFECT_ADJUST_DISTRICT_YIELD_BASED_ON_ADJACENCY_BONUS'),
	('MODIFIER_SINGLE_CITY_ADJUST_PROPERTY',																	'COLLECTION_OWNER',								'EFFECT_ADJUST_CITY_PROPERTY');

---------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Tables
---------------------------------------------------------------------------------------------------------------------------------------------------------------
create table 'HDMonopolyResourceClasses'(
	'Category' TEXT NOT NULL,
	PRIMARY KEY(Category)
);
insert or replace into HDMonopolyResourceClasses (Category) values
	('GROWTH'),
	('FAITH'),
	('GPP'),
	('TRADER'),
	('FOOD'),
	('AMENITY'), -- Default
	('WONDER'),
	('TOURISM'),
	('FISHERY');

-- Resourceful2
insert or replace into HDMonopolyResourceClasses (Category)
select 'ENTERTAINMENT' where exists (select ResourceType from Resources where ResourceType = 'RESOURCE_GRANITE');
insert or replace into HDMonopolyResourceClasses (Category)
select 'MEDICINE' where exists (select ResourceType from Resources where ResourceType = 'RESOURCE_GRANITE');

create table 'HDMonopolyResourceEffects'(
	'ResourceType' TEXT NOT NULL,
	'Category' TEXT NOT NULL,
	'IndustryEffect' TEXT NOT NULL,
	'CorporationEffect' TEXT NOT NULL,
	'ProductEffect' TEXT,
	PRIMARY KEY(ResourceType)
	FOREIGN KEY(ResourceType) REFERENCES Resources(ResourceType) ON DELETE CASCADE ON UPDATE CASCADE
	FOREIGN KEY(Category) REFERENCES HDMonopolyResourceClasses(Category) ON DELETE CASCADE ON UPDATE CASCADE
);

---------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Requirements
---------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 鲁尔山谷 Reqs
insert or ignore into RequirementSets (RequirementSetId, RequirementSetType)
	select 'HD_RUHR_VALLEY_SHARE_' || Category || '_INDUSTRY_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL' from HDMonopolyResourceClasses;
insert or ignore into RequirementSetRequirements (RequirementSetId, RequirementId)
	select 'HD_RUHR_VALLEY_SHARE_' || Category || '_INDUSTRY_REQUIREMENTS', 'REQUIRES_HD_RUHR_VALLEY_SHARE_' || Category || '_INDUSTRY' from HDMonopolyResourceClasses;

insert or ignore into Requirements (RequirementId, RequirementType)
	select 'REQUIRES_HD_RUHR_VALLEY_SHARE_' || Category || '_INDUSTRY', 'REQUIREMENT_PLOT_PROPERTY_MATCHES' from HDMonopolyResourceClasses;
insert or ignore into RequirementArguments (RequirementId, Name, Value)
	select 'REQUIRES_HD_RUHR_VALLEY_SHARE_' || Category || '_INDUSTRY', 'PropertyName', 'HD_RUHR_VALLEY_SHARE_' || Category || '_INDUSTRY' from HDMonopolyResourceClasses;
insert or ignore into RequirementArguments (RequirementId, Name, Value)
	select 'REQUIRES_HD_RUHR_VALLEY_SHARE_' || Category || '_INDUSTRY', 'PropertyMinimum', 1 from HDMonopolyResourceClasses;

insert or ignore into Requirements
	(RequirementId,							RequirementType)
values
	('REQUIRES_CITY_HAS_CANAL',				'REQUIREMENT_CITY_HAS_DISTRICT'),
	('HD_REQUIRES_DISTRICT_IS_NOT_DISTRICT_WONDER','REQUIREMENT_DISTRICT_TYPE_MATCHES'),
	('REQUIRES_CITY_HAS_NO_BUILDING_CANAL','REQUIREMENT_CITY_HAS_BUILDING'),
	('HD_PLOT_ADJACENT_TO_IMPROVEMENT_WAREHOUSE_OR_CONTAINER_PORT','REQUIREMENT_REQUIREMENTSET_IS_MET'),
	('HD_REQUIRES_RIVER_OR_ON_OR_ADJACENT_TO_COAST','REQUIREMENT_REQUIREMENTSET_IS_MET');

update Requirements set Inverse = 1 where RequirementId = 'HD_REQUIRES_DISTRICT_IS_NOT_DISTRICT_WONDER';
update Requirements set Inverse = 1 where RequirementId = 'REQUIRES_CITY_HAS_NO_BUILDING_CANAL';

insert or ignore into RequirementArguments
	(RequirementId,							Name,				Value)
values
	('REQUIRES_CITY_HAS_CANAL',				'DistrictType',	'DISTRICT_CANAL'),
	('HD_REQUIRES_DISTRICT_IS_NOT_DISTRICT_WONDER','DistrictType',  'DISTRICT_WONDER'),
	('REQUIRES_CITY_HAS_NO_BUILDING_CANAL','BuildingType',  'BUILDING_CANAL'),
	('HD_PLOT_ADJACENT_TO_IMPROVEMENT_WAREHOUSE_OR_CONTAINER_PORT','RequirementSetId',  'HD_PLOT_ADJACENT_TO_IMPROVEMENT_WAREHOUSE_OR_CONTAINER_PORT_REQUIRMENTS'),
	('HD_REQUIRES_RIVER_OR_ON_OR_ADJACENT_TO_COAST','RequirementSetId',  'HD_IS_RIVER_OR_ON_OR_ADJACENT_TO_COAST');

insert or ignore into RequirementSets
	(RequirementSetId,										RequirementSetType)
values
	('HD_PLOT_FISHERY_CORP_REQUIREMENTS',					'REQUIREMENTSET_TEST_ALL'),
	('HD_CITY_HAS_CANAL',									'REQUIREMENTSET_TEST_ALL'),
	('PLOT_IS_DISTRICT_ADJACENT_TO_RIVER_OR_ON_OR_ADJACENT_TO_COAST_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
	('HD_CITY_HAS_HARBOR_TIER_1_BUILDING_REQUIREMENTS',		'REQUIREMENTSET_TEST_ANY'),
	('HD_CITY_HAS_HARBOR_TIER_2_BUILDING_REQUIREMENTS',		'REQUIREMENTSET_TEST_ANY'),
	('HD_CITY_HAS_HARBOR_TIER_3_BUILDING_REQUIREMENTS',		'REQUIREMENTSET_TEST_ANY'),
	('CITY_HAS_COMMERCIAL_HUB_AND_PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER',	'REQUIREMENTSET_TEST_ALL'),
	('CITY_HAS_CAMPUS_AND_PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER',			'REQUIREMENTSET_TEST_ALL'),
	('CITY_HAS_BUILDING_EXHIBITION_REQUIREMENTS',			'REQUIREMENTSET_TEST_ALL'),
	('HD_CITY_HAS_BUILDING_EXHIBITION_NO_BUILDING_CANAL',			'REQUIREMENTSET_TEST_ALL'),
	('HD_CITY_HAS_IMPROVED_GROWTH_FOOD_FISHERY_RESOURCE_REQUIRMENTS',			'REQUIREMENTSET_TEST_ANY'),
	('HD_CITY_HAS_IMPROVED_TRADER_ENTERTAINMENT_RESOURCE_REQUIRMENTS',			'REQUIREMENTSET_TEST_ANY'),
	('HD_PLOT_ADJACENT_TO_IMPROVEMENT_WAREHOUSE_OR_CONTAINER_PORT_REQUIRMENTS',  			'REQUIREMENTSET_TEST_ANY'),
	('HD_WAREHOUSE_MANAGEMENT_COMMERCIAL_HUB_REQUIRMENTS',  			'REQUIREMENTSET_TEST_ALL'),
	('HD_WAREHOUSE_MANAGEMENT_HARBOR_REQUIRMENTS',  							'REQUIREMENTSET_TEST_ALL'),
	('HD_WAREHOUSE_MANAGEMENT_INDUSTRIAL_ZONE_REQUIRMENTS',  			'REQUIREMENTSET_TEST_ALL'),
	('HD_PLOT_HAS_INDUSTRY_OR_CORPORATION_REQUIRMENTS',  			'REQUIREMENTSET_TEST_ANY'),
	('HD_IS_RIVER_OR_ON_OR_ADJACENT_TO_COAST',							'REQUIREMENTSET_TEST_ANY');

insert or ignore into RequirementSetRequirements
	(RequirementSetId,						RequirementId)
values
	('HD_PLOT_FISHERY_CORP_REQUIREMENTS',	'REQUIRES_PLOT_HAS_IMPROVEMENT_FISHERY'),
	('HD_PLOT_FISHERY_CORP_REQUIREMENTS',	'REQUIRES_PLOT_ADJACENT_TO_IMPROVEMENT_FISHING_BOATS'),
	('HD_CITY_HAS_CANAL',					'REQUIRES_CITY_HAS_CANAL'),
	('HD_CITY_HAS_HARBOR_TIER_1_BUILDING_REQUIREMENTS','REQUIRES_CITY_HAS_BUILDING_LIGHTHOUSE'),
	('HD_CITY_HAS_HARBOR_TIER_2_BUILDING_REQUIREMENTS','REQUIRES_CITY_HAS_BUILDING_SHIPYARD'),
	('HD_CITY_HAS_HARBOR_TIER_3_BUILDING_REQUIREMENTS','REQUIRES_CITY_HAS_BUILDING_SEAPORT'),
	('PLOT_IS_DISTRICT_ADJACENT_TO_RIVER_OR_ON_OR_ADJACENT_TO_COAST_REQUIREMENTS','REQUIRES_PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER'),
	('PLOT_IS_DISTRICT_ADJACENT_TO_RIVER_OR_ON_OR_ADJACENT_TO_COAST_REQUIREMENTS','HD_REQUIRES_RIVER_OR_ON_OR_ADJACENT_TO_COAST'),
	('CITY_HAS_COMMERCIAL_HUB_AND_PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER',	'REQUIRES_PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER'),
	('CITY_HAS_COMMERCIAL_HUB_AND_PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER',	'REQUIRES_CITY_HAS_DISTRICT_COMMERCIAL_HUB'),
	('CITY_HAS_CAMPUS_AND_PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER',	'REQUIRES_PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER'),
	('CITY_HAS_CAMPUS_AND_PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER',	'REQUIRES_CITY_HAS_DISTRICT_CAMPUS'),
	('CITY_HAS_BUILDING_EXHIBITION_REQUIREMENTS',			'REQUIRES_CITY_HAS_BUILDING_EXHIBITION'),
	('HD_CITY_HAS_BUILDING_EXHIBITION_NO_BUILDING_CANAL',			'REQUIRES_CITY_HAS_BUILDING_EXHIBITION'),
	('HD_CITY_HAS_BUILDING_EXHIBITION_NO_BUILDING_CANAL',			'REQUIRES_CITY_HAS_NO_BUILDING_CANAL'),
	('HD_CITY_HAS_IMPROVED_GROWTH_FOOD_FISHERY_RESOURCE_REQUIRMENTS',			'REQUIRES_HD_CITY_HAS_IMPROVED_GROWTH_RESOURCE'),
	('HD_CITY_HAS_IMPROVED_GROWTH_FOOD_FISHERY_RESOURCE_REQUIRMENTS',			'REQUIRES_HD_CITY_HAS_IMPROVED_FOOD_RESOURCE'),
	('HD_CITY_HAS_IMPROVED_GROWTH_FOOD_FISHERY_RESOURCE_REQUIRMENTS',			'REQUIRES_HD_CITY_HAS_IMPROVED_FISHERY_RESOURCE'),
	('HD_CITY_HAS_IMPROVED_TRADER_ENTERTAINMENT_RESOURCE_REQUIRMENTS',			'REQUIRES_HD_CITY_HAS_IMPROVED_TRADER_RESOURCE'),
	('HD_PLOT_ADJACENT_TO_IMPROVEMENT_WAREHOUSE_OR_CONTAINER_PORT_REQUIRMENTS',			'REQUIRES_PLOT_ADJACENT_TO_IMPROVEMENT_LEU_WAREHOUSE'),
	('HD_PLOT_ADJACENT_TO_IMPROVEMENT_WAREHOUSE_OR_CONTAINER_PORT_REQUIRMENTS',			'REQUIRES_PLOT_ADJACENT_TO_IMPROVEMENT_LEU_CONTAINER_PORT'),
	('HD_WAREHOUSE_MANAGEMENT_COMMERCIAL_HUB_REQUIRMENTS',			'HD_PLOT_ADJACENT_TO_IMPROVEMENT_WAREHOUSE_OR_CONTAINER_PORT'),
	('HD_WAREHOUSE_MANAGEMENT_COMMERCIAL_HUB_REQUIRMENTS',			'REQUIRES_DISTRICT_IS_COMMERCIAL_HUB'),
	('HD_WAREHOUSE_MANAGEMENT_HARBOR_REQUIRMENTS',							'HD_PLOT_ADJACENT_TO_IMPROVEMENT_WAREHOUSE_OR_CONTAINER_PORT'),
	('HD_WAREHOUSE_MANAGEMENT_HARBOR_REQUIRMENTS',							'REQUIRES_DISTRICT_IS_HARBOR'),
	('HD_WAREHOUSE_MANAGEMENT_INDUSTRIAL_ZONE_REQUIRMENTS',			'HD_PLOT_ADJACENT_TO_IMPROVEMENT_WAREHOUSE_OR_CONTAINER_PORT'),
	('HD_WAREHOUSE_MANAGEMENT_INDUSTRIAL_ZONE_REQUIRMENTS',			'REQUIRES_DISTRICT_IS_INDUSTRIAL_ZONE'),
	('HD_PLOT_HAS_INDUSTRY_OR_CORPORATION_REQUIRMENTS',			'REQUIRES_PLOT_HAS_IMPROVEMENT_INDUSTRY'),
	('HD_PLOT_HAS_INDUSTRY_OR_CORPORATION_REQUIRMENTS',			'REQUIRES_PLOT_HAS_IMPROVEMENT_CORPORATION'),
	('HD_IS_RIVER_OR_ON_OR_ADJACENT_TO_COAST',							'REQUIRES_PLOT_IS_COAST'),
	('HD_IS_RIVER_OR_ON_OR_ADJACENT_TO_COAST',							'REQUIRES_PLOT_IS_ADJACENT_TO_COAST'),
	('HD_IS_RIVER_OR_ON_OR_ADJACENT_TO_COAST',							'REQUIRES_PLOT_ADJACENT_TO_RIVER');