-- =====================================================================================================================================
-- 删除垄断加成
-- =====================================================================================================================================
insert or replace into GlobalParameters (Name, Value) values 
	('MONOPOLY_REQUIRED_RESOURCE_CONTROL_PERCENTAGE',			201),
	('MONOPOLY_REQUIRED_RESOURCE_CONTROL_PERCENTAGE_MED',	201),
	('MONOPOLY_REQUIRED_RESOURCE_CONTROL_PERCENTAGE_MAX',	201);

-- =====================================================================================================================================
-- 行业公司有效资源 补充源于Mod的资源
-- =====================================================================================================================================
insert or ignore into Improvement_ValidResources (ImprovementType, ResourceType) select distinct
	'IMPROVEMENT_INDUSTRY', ResourceType
from HD_Monopoly_Resource_Categories where ResourceType in (select ResourceType from Resources where ResourceClassType = 'RESOURCECLASS_LUXURY');

insert or ignore into Improvement_ValidResources (ImprovementType, ResourceType) select distinct
	'IMPROVEMENT_CORPORATION', ResourceType
from HD_Monopoly_Resource_Categories where ResourceType in (select ResourceType from Resources where ResourceClassType = 'RESOURCECLASS_LUXURY');

update Improvement_ValidResources set MustRemoveFeature = 0 where ImprovementType = 'IMPROVEMENT_INDUSTRY';
update Improvement_ValidResources set MustRemoveFeature = 0 where ImprovementType = 'IMPROVEMENT_CORPORATION';

-- =====================================================================================================================================
-- 行业公司产出
-- =====================================================================================================================================
update Improvement_YieldChanges set YieldChange = 4
	where ImprovementType = 'IMPROVEMENT_INDUSTRY' and YieldType = 'YIELD_FOOD';
update Improvement_YieldChanges set YieldChange = 4
	where ImprovementType = 'IMPROVEMENT_INDUSTRY' and YieldType = 'YIELD_PRODUCTION';
delete from Improvement_YieldChanges where ImprovementType = 'IMPROVEMENT_INDUSTRY' and YieldType = 'YIELD_GOLD';

update Improvement_YieldChanges set YieldChange = 6
	where ImprovementType = 'IMPROVEMENT_CORPORATION' and YieldType = 'YIELD_FOOD';
update Improvement_YieldChanges set YieldChange = 6
	where ImprovementType = 'IMPROVEMENT_CORPORATION' and YieldType = 'YIELD_PRODUCTION';
update Improvement_YieldChanges set YieldChange = 9
	where ImprovementType = 'IMPROVEMENT_CORPORATION' and YieldType = 'YIELD_GOLD';
update Improvements set Removable = 0 where ImprovementType = 'IMPROVEMENT_CORPORATION';

-- =====================================================================================================================================
-- 行业公司特效
-- =====================================================================================================================================
-- 删除旧特效
delete from ImprovementModifiers where ImprovementType = 'IMPROVEMENT_INDUSTRY';
delete from ImprovementModifiers where ImprovementType = 'IMPROVEMENT_CORPORATION';

-- =========================
-- 行业特效
-- =========================
insert or ignore into HD_IndustryModifiers (Category, ModifierId) values
	('CROPS',						'HD_CROPS_INDUSTRY_IMPROVEMENT_YIELD'),
	('AGRICULTURE',			'HD_AGRICULTURE_INDUSTRY_POP_FOOD'),
	('CUISINE',					'HD_CUISINE_INDUSTRY_CITY_PROPERTY'),
	('FRUIT',						'HD_FRUIT_INDUSTRY_CITY_PROPERTY'),
	('BREWING',					'HD_BREWING_INDUSTRY_IMPROVEMENT_YIELD'),
	('BREWING',					'HD_BREWING_INDUSTRY_DISTRICT_CULTURE'),
	('BREWING',					'HD_BREWING_INDUSTRY_DISTRICT_GOLD'),
	('BEVERAGE',				'HD_BEVERAGE_INDUSTRY_POP_SCIENCE'),
	('BEVERAGE',				'HD_BEVERAGE_INDUSTRY_POP_CULTURE'),
	('OIL',							'HD_OIL_INDUSTRY_POP_PRODUCTION'),
	('LEATHER',					'HD_LEATHER_INDUSTRY_CITY_PROPERTY'),
	('CLOTH',						'HD_CLOTH_INDUSTRY_TIER1_CULTURE_ATTACH'),
	('CLOTH',						'HD_CLOTH_INDUSTRY_TIER1_GOLD_ATTACH'),
	('CLOTH',						'HD_CLOTH_INDUSTRY_TIER2_CULTURE_ATTACH'),
	('CLOTH',						'HD_CLOTH_INDUSTRY_TIER2_GOLD_ATTACH'),
	('CLOTH',						'HD_CLOTH_INDUSTRY_TIER3_CULTURE_ATTACH'),
	('CLOTH',						'HD_CLOTH_INDUSTRY_TIER3_GOLD_ATTACH'),
	('CLOTH',						'HD_CLOTH_INDUSTRY_TIER4_CULTURE_ATTACH'),
	('CLOTH',						'HD_CLOTH_INDUSTRY_TIER4_GOLD_ATTACH'),
	('CONSTRUCTION',		'HD_CONSTRUCTION_INDUSTRY_WONDER_SPEED'),
	('FUEL',						'HD_FUEL_INDUSTRY_TIER1_PRODUCTION_ATTACH'),
	('FUEL',						'HD_FUEL_INDUSTRY_TIER2_PRODUCTION_ATTACH'),
	('FUEL',						'HD_FUEL_INDUSTRY_TIER3_PRODUCTION_ATTACH'),
	('CHEMISTRY',				'HD_CHEMISTRY_INDUSTRY_CAMPUS'),
	('CHEMISTRY',				'HD_CHEMISTRY_INDUSTRY_INDUSTRIAL_ZONE'),
	('METALLURGY',			'HD_METALLURGY_INDUSTRY_IMPROVEMENT_YIELD'),
	('MINTING',					'HD_MINTING_INDUSTRY_TRADE_ROUTE_CAPACITY'),
	('MINTING',					'HD_MINTING_INDUSTRY_COMMERCIAL_HUB'),
	('TRANSIT',					'HD_TRANSIT_INDUSTRY_PASTURE_YIELD'),
	('TRANSIT',					'HD_TRANSIT_INDUSTRY_IMPROVEMENT_YIELD'),
	('SEASONING',				'HD_SEASONING_INDUSTRY_GOLD'),
	('SEAFOOD',					'HD_SEAFOOD_INDUSTRY_HARBOR_FOOD'),
	('MARINE_PRODUCTS',	'HD_MARINE_PRODUCTS_INDUSTRY_HARBOR_PRODUCTION'),
	('SEA_BEAST',				'HD_SEA_BEAST_INDUSTRY_IMPROVEMENT_YIELD'),
	('CELEBRATION',			'HD_CELEBRATION_INDUSTRY_DISTRICT'),
	('CELEBRATION',			'HD_CELEBRATION_INDUSTRY_IMPROVEMENT'),
	('MEDICINE',				'HD_MEDICINE_INDUSTRY_DISTRICT_SCIENCE'),
	('MEDICINE',				'HD_MEDICINE_INDUSTRY_DISTRICT_FAITH'),
	('STATIONERY',			'HD_STATIONERY_INDUSTRY_IMPROVEMENT_YIELD'),
	('ART',							'HD_ART_INDUSTRY_WRITER'),
	('ART',							'HD_ART_INDUSTRY_ARTIST'),
	('ART',							'HD_ART_INDUSTRY_MUSICIAN'),
	('DECORATION',			'HD_DECORATION_INDUSTRY_DISTRICT_CULTURE'),
	('DECORATION',			'HD_DECORATION_INDUSTRY_DISTRICT_GOLD'),
	('ORNAMENTAL',			'HD_ORNAMENTAL_INDUSTRY_APPEAL'),
	('ORNAMENTAL',			'HD_ORNAMENTAL_INDUSTRY_PLOT_YIELD'),
	('BEAST',						'HD_BEAST_INDUSTRY_CITY_PROPERTY'),
	('HOUSEHOLD',				'HD_HOUSEHOLD_INDUSTRY_IMPROVEMENT_YIELD');

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) values
	('HD_CROPS_INDUSTRY_IMPROVEMENT_YIELD',							'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',													'HD_CROPS_INDUSTRY_BONUS_REQUIREMENTS',							'PLOT_HAS_IMPROVEMENT_CLASSIFICATION_AGRICULTURAL_PRODUCTION_REQUIREMENTS'),
	('HD_AGRICULTURE_INDUSTRY_POP_FOOD',								'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',								'HD_AGRICULTURE_INDUSTRY_BONUS_REQUIREMENTS',				NULL),
	('HD_CUISINE_INDUSTRY_CITY_PROPERTY',								'MODIFIER_SINGLE_CITY_ADJUST_PROPERTY',																	'HD_CUISINE_INDUSTRY_BONUS_REQUIREMENTS',						NULL),
	('HD_FRUIT_INDUSTRY_CITY_PROPERTY',									'MODIFIER_SINGLE_CITY_ADJUST_PROPERTY',																	'HD_FRUIT_INDUSTRY_BONUS_REQUIREMENTS',							NULL),
	('HD_BREWING_INDUSTRY_IMPROVEMENT_YIELD',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',													'HD_BREWING_INDUSTRY_BONUS_REQUIREMENTS',						'HD_IMPROVEMENT_ADJACENT_TO_WATER_CONSERVANCY_FACILITIES_REQUIREMENTS'),
	('HD_BREWING_INDUSTRY_DISTRICT_CULTURE',						'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE',													'HD_BREWING_INDUSTRY_BONUS_REQUIREMENTS',						'HD_DISTRICT_ADJACENT_TO_WATER_CONSERVANCY_FACILITIES_REQUIREMENTS'),
	('HD_BREWING_INDUSTRY_DISTRICT_GOLD',								'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE',													'HD_BREWING_INDUSTRY_BONUS_REQUIREMENTS',						'HD_DISTRICT_ADJACENT_TO_WATER_CONSERVANCY_FACILITIES_REQUIREMENTS'),
	('HD_BEVERAGE_INDUSTRY_POP_SCIENCE',								'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',								'HD_BEVERAGE_INDUSTRY_BONUS_REQUIREMENTS',					NULL),
	('HD_BEVERAGE_INDUSTRY_POP_CULTURE',								'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',								'HD_BEVERAGE_INDUSTRY_BONUS_REQUIREMENTS',					NULL),
	('HD_OIL_INDUSTRY_POP_PRODUCTION',									'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',								'HD_OIL_INDUSTRY_BONUS_REQUIREMENTS',								NULL),
	('HD_LEATHER_INDUSTRY_CITY_PROPERTY',								'MODIFIER_SINGLE_CITY_ADJUST_PROPERTY',																	'HD_LEATHER_INDUSTRY_BONUS_REQUIREMENTS',						NULL),
	('HD_CLOTH_INDUSTRY_TIER1_CULTURE_ATTACH',					'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_CLOTH_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_COMMERCIAL_HUB_TIER_1_BUILDING_REQUIREMENTS'),
	('HD_CLOTH_INDUSTRY_TIER1_GOLD_ATTACH',							'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_CLOTH_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_COMMERCIAL_HUB_TIER_1_BUILDING_REQUIREMENTS'),
	('HD_CLOTH_INDUSTRY_TIER2_CULTURE_ATTACH',					'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_CLOTH_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_COMMERCIAL_HUB_TIER_2_BUILDING_REQUIREMENTS'),
	('HD_CLOTH_INDUSTRY_TIER2_GOLD_ATTACH',							'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_CLOTH_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_COMMERCIAL_HUB_TIER_2_BUILDING_REQUIREMENTS'),
	('HD_CLOTH_INDUSTRY_TIER3_CULTURE_ATTACH',					'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_CLOTH_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_COMMERCIAL_HUB_TIER_3_BUILDING_REQUIREMENTS'),
	('HD_CLOTH_INDUSTRY_TIER3_GOLD_ATTACH',							'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_CLOTH_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_COMMERCIAL_HUB_TIER_3_BUILDING_REQUIREMENTS'),
	('HD_CLOTH_INDUSTRY_TIER4_CULTURE_ATTACH',					'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_CLOTH_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_COMMERCIAL_HUB_TIER_4_BUILDING_REQUIREMENTS'),
	('HD_CLOTH_INDUSTRY_TIER4_GOLD_ATTACH',							'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_CLOTH_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_COMMERCIAL_HUB_TIER_4_BUILDING_REQUIREMENTS'),
	('HD_CLOTH_INDUSTRY_DISTRICT_CULTURE',							'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',												NULL,																								'HD_DISTRICT_IS_CITY_CENTER_OR_NEIGHBORHOOD_WITHIN_6_TILES_REQUIREMENTS'),
	('HD_CLOTH_INDUSTRY_DISTRICT_GOLD',									'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',												NULL,																								'HD_DISTRICT_IS_CITY_CENTER_OR_NEIGHBORHOOD_WITHIN_6_TILES_REQUIREMENTS'),
	('HD_CONSTRUCTION_INDUSTRY_WONDER_SPEED',						'MODIFIER_SINGLE_CITY_ADJUST_WONDER_PRODUCTION',												NULL,																								NULL),
	('HD_FUEL_INDUSTRY_TIER1_PRODUCTION_ATTACH',				'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_FUEL_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_INDUSTRIAL_ZONE_TIER_1_BUILDING_REQUIREMENTS'),
	('HD_FUEL_INDUSTRY_TIER2_PRODUCTION_ATTACH',				'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_FUEL_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_INDUSTRIAL_ZONE_TIER_2_BUILDING_REQUIREMENTS'),
	('HD_FUEL_INDUSTRY_TIER3_PRODUCTION_ATTACH',				'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER',															'HD_FUEL_INDUSTRY_BONUS_REQUIREMENTS',							'HD_PLOT_HAS_DISTRICT_INDUSTRIAL_ZONE_TIER_3_BUILDING_REQUIREMENTS'),
	('HD_FUEL_INDUSTRY_DISTRICT_PRODUCTION',						'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',												NULL,																								'HD_DISTRICT_IS_CITY_CENTER_OR_NEIGHBORHOOD_WITHIN_6_TILES_REQUIREMENTS'),
	('HD_CHEMISTRY_INDUSTRY_CAMPUS',										'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER',												'HD_CHEMISTRY_INDUSTRY_BONUS_REQUIREMENTS',					'DISTRICT_IS_CAMPUS'),
	('HD_CHEMISTRY_INDUSTRY_INDUSTRIAL_ZONE',						'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER',												'HD_CHEMISTRY_INDUSTRY_BONUS_REQUIREMENTS',					'DISTRICT_IS_INDUSTRIAL_ZONE'),
	('HD_METALLURGY_INDUSTRY_IMPROVEMENT_YIELD',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',													'HD_METALLURGY_INDUSTRY_BONUS_REQUIREMENTS',				'PLOT_HAS_IMPROVEMENT_CLASSIFICATION_INDUSTRIAL_PRODUCTION_REQUIREMENTS'),
	('HD_MINTING_INDUSTRY_TRADE_ROUTE_CAPACITY',				'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',													'HD_MINTING_INDUSTRY_BONUS_REQUIREMENTS',						NULL),
	('HD_MINTING_INDUSTRY_COMMERCIAL_HUB',							'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER',												'HD_MINTING_INDUSTRY_BONUS_REQUIREMENTS',						'DISTRICT_IS_COMMERCIAL_HUB'),
	('HD_TRANSIT_INDUSTRY_PASTURE_YIELD',								'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',																		'HD_TRANSIT_INDUSTRY_BONUS_REQUIREMENTS',						'PLOT_HAS_PASTURE_WITH_6_TILES_REQUIRMENTS'),
	('HD_TRANSIT_INDUSTRY_IMPROVEMENT_YIELD',						'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',																		'HD_TRANSIT_INDUSTRY_BONUS_REQUIREMENTS',						'PLOT_HAS_IMPROVEMENT_CLASSIFICATION_COMMERCIAL_FACILITIES_WITH_6_TILES_REQUIRMENTS'),
	('HD_SEASONING_INDUSTRY_GOLD',											'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER',											'HD_SEASONING_INDUSTRY_BONUS_REQUIREMENTS',					NULL),
	('HD_SEAFOOD_INDUSTRY_HARBOR_FOOD',									'MODIFIER_SINGLE_CITY_DISTRICT_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',	'HD_SEAFOOD_INDUSTRY_BONUS_REQUIREMENTS',						'DISTRICT_IS_HARBOR'),
	('HD_MARINE_PRODUCTS_INDUSTRY_HARBOR_PRODUCTION',		'MODIFIER_SINGLE_CITY_DISTRICT_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',	'HD_MARINE_PRODUCTS_INDUSTRY_BONUS_REQUIREMENTS',		'DISTRICT_IS_HARBOR'),
	('HD_SEA_BEAST_INDUSTRY_IMPROVEMENT_YIELD',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',													'HD_SEA_BEAST_INDUSTRY_BONUS_REQUIREMENTS',					'PLOT_HAS_IMPROVEMENT_CLASSIFICATION_WATER_PRODUCTION_REQUIREMENTS'),
	('HD_CELEBRATION_INDUSTRY_DISTRICT',								'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',													'HD_CELEBRATION_INDUSTRY_BONUS_REQUIREMENTS',				'PLOT_ADJACENT_TO_DISTRICT_HOLY_SITE_REQUIREMENTS'),
	('HD_CELEBRATION_INDUSTRY_IMPROVEMENT',							'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',													'HD_CELEBRATION_INDUSTRY_BONUS_REQUIREMENTS',				'PLOT_ADJACENT_TO_IMPROVEMENT_CLASSIFICATION_RELIGIOUS_FACILITIES_REQUIREMENTS'),
	('HD_MEDICINE_INDUSTRY_DISTRICT_SCIENCE',						'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE',													'HD_MEDICINE_INDUSTRY_BONUS_REQUIREMENTS',					'PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER'),
	('HD_MEDICINE_INDUSTRY_DISTRICT_FAITH',							'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE',													'HD_MEDICINE_INDUSTRY_BONUS_REQUIREMENTS',					'PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER'),
	('HD_STATIONERY_INDUSTRY_IMPROVEMENT_YIELD',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',													'HD_STATIONERY_INDUSTRY_BONUS_REQUIREMENTS',				'PLOT_HAS_IMPROVEMENT_CLASSIFICATION_RESEARCH_FACILITIES_REQUIREMENTS'),
	('HD_ART_INDUSTRY_WRITER',													'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS',						'HD_ART_INDUSTRY_BONUS_REQUIREMENTS',								'PLOT_HAS_COMPLETE_WONDER'),
	('HD_ART_INDUSTRY_ARTIST',													'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS',						'HD_ART_INDUSTRY_BONUS_REQUIREMENTS',								'PLOT_HAS_COMPLETE_WONDER'),
	('HD_ART_INDUSTRY_MUSICIAN',												'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS',						'HD_ART_INDUSTRY_BONUS_REQUIREMENTS',								'PLOT_HAS_COMPLETE_WONDER'),
	('HD_DECORATION_INDUSTRY_DISTRICT_CULTURE',					'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE',													'HD_DECORATION_INDUSTRY_BONUS_REQUIREMENTS',				'PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER'),
	('HD_DECORATION_INDUSTRY_DISTRICT_GOLD',						'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE',													'HD_DECORATION_INDUSTRY_BONUS_REQUIREMENTS',				'PLOT_DOES_NOT_HAVE_INCOMPLETE_WONDER'),
	('HD_ORNAMENTAL_INDUSTRY_APPEAL',										'MODIFIER_SINGLE_CITY_ADJUST_CITY_APPEAL',															'HD_ORNAMENTAL_INDUSTRY_BONUS_REQUIREMENTS',				NULL),
	('HD_ORNAMENTAL_INDUSTRY_PLOT_YIELD',								'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',													'HD_ORNAMENTAL_INDUSTRY_BONUS_REQUIREMENTS',				'PLOT_BREATHTAKING_APPEAL'),
	('HD_BEAST_INDUSTRY_CITY_PROPERTY',									'MODIFIER_SINGLE_CITY_ADJUST_PROPERTY',																	'HD_BEAST_INDUSTRY_BONUS_REQUIREMENTS',							NULL),
	('HD_HOUSEHOLD_INDUSTRY_IMPROVEMENT_YIELD',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',													'HD_HOUSEHOLD_INDUSTRY_BONUS_REQUIREMENTS',				  'PLOT_HAS_IMPROVEMENT_CLASSIFICATION_RESIDENTIAL_FACILITIES_REQUIREMENTS');

insert or ignore into ModifierArguments (ModifierId, Name, Value) values
	('HD_CROPS_INDUSTRY_IMPROVEMENT_YIELD',							'YieldType',						'YIELD_FOOD,YIELD_PRODUCTION'),
	('HD_CROPS_INDUSTRY_IMPROVEMENT_YIELD',  						'Amount',								'2,2'),
	('HD_AGRICULTURE_INDUSTRY_POP_FOOD',								'YieldType',						'YIELD_FOOD'),
	('HD_AGRICULTURE_INDUSTRY_POP_FOOD',  							'Amount',								1),
	('HD_CUISINE_INDUSTRY_CITY_PROPERTY',								'Key',									'HD_CITY_NEED_COUNT_POSITIVE_AMENITY'),
	('HD_CUISINE_INDUSTRY_CITY_PROPERTY',  							'Amount',								1),
	('HD_FRUIT_INDUSTRY_CITY_PROPERTY',									'Key',									'HD_CITY_NEED_COUNT_POSITIVE_AMENITY'),
	('HD_FRUIT_INDUSTRY_CITY_PROPERTY',  								'Amount',								1),
	('HD_BREWING_INDUSTRY_IMPROVEMENT_YIELD',						'YieldType',						'YIELD_CULTURE,YIELD_GOLD'),
	('HD_BREWING_INDUSTRY_IMPROVEMENT_YIELD',						'Amount',								'1,6'),
	('HD_BREWING_INDUSTRY_DISTRICT_CULTURE',						'YieldType',						'YIELD_CULTURE'),
	('HD_BREWING_INDUSTRY_DISTRICT_CULTURE',  					'Amount',								1),
	('HD_BREWING_INDUSTRY_DISTRICT_GOLD',								'YieldType',						'YIELD_GOLD'),
	('HD_BREWING_INDUSTRY_DISTRICT_GOLD',  							'Amount',								6),
	('HD_BEVERAGE_INDUSTRY_POP_SCIENCE',								'YieldType',						'YIELD_SCIENCE'),
	('HD_BEVERAGE_INDUSTRY_POP_SCIENCE',  							'Amount',								0.5),
	('HD_BEVERAGE_INDUSTRY_POP_CULTURE',								'YieldType',						'YIELD_CULTURE'),
	('HD_BEVERAGE_INDUSTRY_POP_CULTURE',  							'Amount',								0.5),
	('HD_OIL_INDUSTRY_POP_PRODUCTION',									'YieldType',						'YIELD_PRODUCTION'),
	('HD_OIL_INDUSTRY_POP_PRODUCTION',  								'Amount',								1),
	('HD_LEATHER_INDUSTRY_CITY_PROPERTY',								'Key',									'HD_CITY_NEED_COUNT_POSITIVE_AMENITY'),
	('HD_LEATHER_INDUSTRY_CITY_PROPERTY', 							'Amount',								1),
	('HD_CLOTH_INDUSTRY_TIER1_CULTURE_ATTACH', 					'ModifierId',						'HD_CLOTH_INDUSTRY_DISTRICT_CULTURE'),
	('HD_CLOTH_INDUSTRY_TIER1_GOLD_ATTACH', 						'ModifierId',						'HD_CLOTH_INDUSTRY_DISTRICT_GOLD'),
	('HD_CLOTH_INDUSTRY_TIER2_CULTURE_ATTACH', 					'ModifierId',						'HD_CLOTH_INDUSTRY_DISTRICT_CULTURE'),
	('HD_CLOTH_INDUSTRY_TIER2_GOLD_ATTACH', 						'ModifierId',						'HD_CLOTH_INDUSTRY_DISTRICT_GOLD'),
	('HD_CLOTH_INDUSTRY_TIER3_CULTURE_ATTACH', 					'ModifierId',						'HD_CLOTH_INDUSTRY_DISTRICT_CULTURE'),
	('HD_CLOTH_INDUSTRY_TIER3_GOLD_ATTACH', 						'ModifierId',						'HD_CLOTH_INDUSTRY_DISTRICT_GOLD'),
	('HD_CLOTH_INDUSTRY_TIER4_CULTURE_ATTACH', 					'ModifierId',						'HD_CLOTH_INDUSTRY_DISTRICT_CULTURE'),
	('HD_CLOTH_INDUSTRY_TIER4_GOLD_ATTACH', 						'ModifierId',						'HD_CLOTH_INDUSTRY_DISTRICT_GOLD'),
	('HD_CLOTH_INDUSTRY_DISTRICT_CULTURE',							'YieldType',						'YIELD_CULTURE'),
	('HD_CLOTH_INDUSTRY_DISTRICT_CULTURE',  						'Amount',								1),
	('HD_CLOTH_INDUSTRY_DISTRICT_GOLD',									'YieldType',						'YIELD_GOLD'),
	('HD_CLOTH_INDUSTRY_DISTRICT_GOLD',  								'Amount',								3),
	('HD_CONSTRUCTION_INDUSTRY_WONDER_SPEED', 					'Amount',								10),
	('HD_FUEL_INDUSTRY_TIER1_PRODUCTION_ATTACH', 				'ModifierId',						'HD_FUEL_INDUSTRY_DISTRICT_PRODUCTION'),
	('HD_FUEL_INDUSTRY_TIER2_PRODUCTION_ATTACH', 				'ModifierId',						'HD_FUEL_INDUSTRY_DISTRICT_PRODUCTION'),
	('HD_FUEL_INDUSTRY_TIER3_PRODUCTION_ATTACH', 				'ModifierId',						'HD_FUEL_INDUSTRY_DISTRICT_PRODUCTION'),
	('HD_FUEL_INDUSTRY_DISTRICT_PRODUCTION',						'YieldType',						'YIELD_PRODUCTION'),
	('HD_FUEL_INDUSTRY_DISTRICT_PRODUCTION',						'Amount',								2),
	('HD_CHEMISTRY_INDUSTRY_CAMPUS',										'YieldType',						'YIELD_SCIENCE'),
	('HD_CHEMISTRY_INDUSTRY_CAMPUS',										'Amount',								100),
	('HD_CHEMISTRY_INDUSTRY_INDUSTRIAL_ZONE',						'YieldType',						'YIELD_PRODUCTION'),
	('HD_CHEMISTRY_INDUSTRY_INDUSTRIAL_ZONE',						'Amount',								100),
	('HD_METALLURGY_INDUSTRY_IMPROVEMENT_YIELD',				'YieldType',						'YIELD_PRODUCTION'),
	('HD_METALLURGY_INDUSTRY_IMPROVEMENT_YIELD',				'Amount',								4),
	('HD_MINTING_INDUSTRY_TRADE_ROUTE_CAPACITY',				'Amount',								1),
	('HD_MINTING_INDUSTRY_COMMERCIAL_HUB',							'YieldType',						'YIELD_GOLD'),
	('HD_MINTING_INDUSTRY_COMMERCIAL_HUB',							'Amount',								100),
	('HD_TRANSIT_INDUSTRY_PASTURE_YIELD',								'YieldType',						'YIELD_PRODUCTION,YIELD_GOLD'),
	('HD_TRANSIT_INDUSTRY_PASTURE_YIELD',								'Amount',								'1,3'),
	('HD_TRANSIT_INDUSTRY_IMPROVEMENT_YIELD',						'YieldType',						'YIELD_PRODUCTION,YIELD_GOLD'),
	('HD_TRANSIT_INDUSTRY_IMPROVEMENT_YIELD',						'Amount',								'1,3'),
	('HD_SEASONING_INDUSTRY_GOLD',											'YieldType',						'YIELD_GOLD'),
	('HD_SEASONING_INDUSTRY_GOLD',											'Amount',								15),
	('HD_SEAFOOD_INDUSTRY_HARBOR_FOOD',									'YieldTypeToMirror',		'YIELD_GOLD'),
	('HD_SEAFOOD_INDUSTRY_HARBOR_FOOD',									'YieldTypeToGrant',			'YIELD_FOOD'),
	('HD_MARINE_PRODUCTS_INDUSTRY_HARBOR_PRODUCTION',		'YieldTypeToMirror',		'YIELD_GOLD'),
	('HD_MARINE_PRODUCTS_INDUSTRY_HARBOR_PRODUCTION',		'YieldTypeToGrant',			'YIELD_PRODUCTION'),
	('HD_SEA_BEAST_INDUSTRY_IMPROVEMENT_YIELD',					'YieldType',						'YIELD_SCIENCE,YIELD_CULTURE'),
	('HD_SEA_BEAST_INDUSTRY_IMPROVEMENT_YIELD',					'Amount',								'1,1'),
	('HD_CELEBRATION_INDUSTRY_DISTRICT',								'YieldType',						'YIELD_CULTURE,YIELD_FAITH'),
	('HD_CELEBRATION_INDUSTRY_DISTRICT',								'Amount',								'1,1'),
	('HD_CELEBRATION_INDUSTRY_IMPROVEMENT',							'YieldType',						'YIELD_CULTURE,YIELD_FAITH'),
	('HD_CELEBRATION_INDUSTRY_IMPROVEMENT',							'Amount',								'1,1'),
	('HD_MEDICINE_INDUSTRY_DISTRICT_SCIENCE',						'YieldType',						'YIELD_SCIENCE'),
	('HD_MEDICINE_INDUSTRY_DISTRICT_SCIENCE',						'Amount',								1),
	('HD_MEDICINE_INDUSTRY_DISTRICT_FAITH',							'YieldType',						'YIELD_FAITH'),
	('HD_MEDICINE_INDUSTRY_DISTRICT_FAITH',							'Amount',								1),
	('HD_STATIONERY_INDUSTRY_IMPROVEMENT_YIELD',				'YieldType',						'YIELD_SCIENCE,YIELD_CULTURE'),
	('HD_STATIONERY_INDUSTRY_IMPROVEMENT_YIELD',				'Amount',								'2,2'),
	('HD_ART_INDUSTRY_WRITER',  												'GreatPersonClassType',	'GREAT_PERSON_CLASS_WRITER'),
	('HD_ART_INDUSTRY_WRITER',  												'Amount',								2),
	('HD_ART_INDUSTRY_ARTIST',  												'GreatPersonClassType',	'GREAT_PERSON_CLASS_ARTIST'),
	('HD_ART_INDUSTRY_ARTIST',  												'Amount',								2),
	('HD_ART_INDUSTRY_MUSICIAN',  											'GreatPersonClassType',	'GREAT_PERSON_CLASS_MUSICIAN'),
	('HD_ART_INDUSTRY_MUSICIAN',  											'Amount',								2),
	('HD_DECORATION_INDUSTRY_DISTRICT_CULTURE',					'YieldType',						'YIELD_CULTURE'),
	('HD_DECORATION_INDUSTRY_DISTRICT_CULTURE',					'Amount',								1),
	('HD_DECORATION_INDUSTRY_DISTRICT_GOLD',						'YieldType',						'YIELD_GOLD'),
	('HD_DECORATION_INDUSTRY_DISTRICT_GOLD',						'Amount',								3),
	('HD_ORNAMENTAL_INDUSTRY_APPEAL',										'Amount',								1),
	('HD_ORNAMENTAL_INDUSTRY_PLOT_YIELD',								'YieldType',						'YIELD_SCIENCE,YIELD_CULTURE'),
	('HD_ORNAMENTAL_INDUSTRY_PLOT_YIELD',								'Amount',								'1,1'),
	('HD_BEAST_INDUSTRY_CITY_PROPERTY',									'Key',									'HD_CITY_NEED_COUNT_POSITIVE_AMENITY'),
	('HD_BEAST_INDUSTRY_CITY_PROPERTY', 								'Amount',								1),
	('HD_HOUSEHOLD_INDUSTRY_IMPROVEMENT_YIELD',					'YieldType',						'YIELD_PRODUCTION'),
	('HD_HOUSEHOLD_INDUSTRY_IMPROVEMENT_YIELD',					'Amount',								2);

-- 美食行业
insert or ignore into HD_IndustryModifiers (Category, ModifierId) select
	'CUISINE', 'HD_CUISINE_INDUSTRY_CITY_CULTURE_' || Exp || '_ATTACH'
from HD_Binary_Compress where Exp < 7;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_CUISINE_INDUSTRY_CITY_CULTURE_' || Exp || '_ATTACH', 'MODIFIER_CITY_OWNER_ATTACH_MODIFIER', 'HD_CUISINE_INDUSTRY_BONUS_REQUIREMENTS', 'HD_PLOT_BINARY_COMPRESS_CITY_POSITIVE_AMENITY_' || Exp || '_REQUIREMENTS'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_CUISINE_INDUSTRY_CITY_CULTURE_' || Exp || '_ATTACH', 'ModifierId', 'HD_CUISINE_INDUSTRY_CITY_CULTURE_' || Exp
from HD_Binary_Compress where Exp < 7;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_CUISINE_INDUSTRY_CITY_CULTURE_' || Exp, 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', NULL, NULL
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_CUISINE_INDUSTRY_CITY_CULTURE_' || Exp, 'YieldType', 'YIELD_CULTURE'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_CUISINE_INDUSTRY_CITY_CULTURE_' || Exp, 'Amount', Amount
from HD_Binary_Compress where Exp < 7;

-- 水果行业
insert or ignore into HD_IndustryModifiers (Category, ModifierId) select
	'FRUIT', 'HD_FRUIT_INDUSTRY_CITY_GOLD_' || Exp || '_ATTACH'
from HD_Binary_Compress where Exp < 7;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_FRUIT_INDUSTRY_CITY_GOLD_' || Exp || '_ATTACH', 'MODIFIER_CITY_OWNER_ATTACH_MODIFIER', 'HD_FRUIT_INDUSTRY_BONUS_REQUIREMENTS', 'HD_PLOT_BINARY_COMPRESS_CITY_POSITIVE_AMENITY_' || Exp || '_REQUIREMENTS'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_FRUIT_INDUSTRY_CITY_GOLD_' || Exp || '_ATTACH', 'ModifierId', 'HD_FRUIT_INDUSTRY_CITY_GOLD_' || Exp
from HD_Binary_Compress where Exp < 7;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_FRUIT_INDUSTRY_CITY_GOLD_' || Exp, 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', NULL, NULL
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_FRUIT_INDUSTRY_CITY_GOLD_' || Exp, 'YieldType', 'YIELD_GOLD'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_FRUIT_INDUSTRY_CITY_GOLD_' || Exp, 'Amount', Amount * 3
from HD_Binary_Compress where Exp < 7;

insert or ignore into HD_IndustryModifiers (Category, ModifierId) select
	'FRUIT', 'HD_FRUIT_INDUSTRY_CITY_GPP_' || Exp || '_ATTACH'
from HD_Binary_Compress where Exp < 7;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_FRUIT_INDUSTRY_CITY_GPP_' || Exp || '_ATTACH', 'MODIFIER_CITY_OWNER_ATTACH_MODIFIER', 'HD_FRUIT_INDUSTRY_BONUS_REQUIREMENTS', 'HD_PLOT_BINARY_COMPRESS_CITY_POSITIVE_AMENITY_' || Exp || '_REQUIREMENTS'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_FRUIT_INDUSTRY_CITY_GPP_' || Exp || '_ATTACH', 'ModifierId', 'HD_FRUIT_INDUSTRY_CITY_GPP_' || Exp
from HD_Binary_Compress where Exp < 7;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_FRUIT_INDUSTRY_CITY_GPP_' || Exp, 'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', NULL, 'DISTRICT_IS_DISTRICT_CITY_CENTER_REQUIREMENTS'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_FRUIT_INDUSTRY_CITY_GPP_' || Exp, 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MERCHANT'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_FRUIT_INDUSTRY_CITY_GPP_' || Exp, 'Amount', Amount
from HD_Binary_Compress where Exp < 7;

-- 皮革行业
insert or ignore into HD_IndustryModifiers (Category, ModifierId) select
	'LEATHER', 'HD_LEATHER_INDUSTRY_CITY_PRODUCTION_' || Exp || '_ATTACH'
from HD_Binary_Compress where Exp < 7;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_LEATHER_INDUSTRY_CITY_PRODUCTION_' || Exp || '_ATTACH', 'MODIFIER_CITY_OWNER_ATTACH_MODIFIER', 'HD_LEATHER_INDUSTRY_BONUS_REQUIREMENTS', 'HD_PLOT_BINARY_COMPRESS_CITY_POSITIVE_AMENITY_' || Exp || '_REQUIREMENTS'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_LEATHER_INDUSTRY_CITY_PRODUCTION_' || Exp || '_ATTACH', 'ModifierId', 'HD_LEATHER_INDUSTRY_CITY_PRODUCTION_' || Exp
from HD_Binary_Compress where Exp < 7;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_LEATHER_INDUSTRY_CITY_PRODUCTION_' || Exp, 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', NULL, NULL
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_LEATHER_INDUSTRY_CITY_PRODUCTION_' || Exp, 'YieldType', 'YIELD_PRODUCTION'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_LEATHER_INDUSTRY_CITY_PRODUCTION_' || Exp, 'Amount', Amount
from HD_Binary_Compress where Exp < 7;

-- 燃料行业（适配JNR工业区拓展）
insert or ignore into HD_IndustryModifiers (Category, ModifierId) select
	'FUEL', 'HD_FUEL_INDUSTRY_TIER4_PRODUCTION_ATTACH'
where exists (select BuildingType from Buildings where BuildingType = 'BUILDING_JNR_MILL_RACE');

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_FUEL_INDUSTRY_TIER4_PRODUCTION_ATTACH', 'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER', 'HD_FUEL_INDUSTRY_BONUS_REQUIREMENTS', 'HD_PLOT_HAS_DISTRICT_INDUSTRIAL_ZONE_TIER_4_BUILDING_REQUIREMENTS'
where exists (select BuildingType from Buildings where BuildingType = 'BUILDING_JNR_MILL_RACE');

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_FUEL_INDUSTRY_TIER3_PRODUCTION_ATTACH', 'ModifierId', 'HD_FUEL_INDUSTRY_DISTRICT_PRODUCTION'
where exists (select BuildingType from Buildings where BuildingType = 'BUILDING_JNR_MILL_RACE');

-- 珍兽行业
insert or ignore into HD_IndustryModifiers (Category, ModifierId) select
	'BEAST', 'HD_BEAST_INDUSTRY_CITY_SCIENCE_' || Exp || '_ATTACH'
from HD_Binary_Compress where Exp < 7;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_BEAST_INDUSTRY_CITY_SCIENCE_' || Exp || '_ATTACH', 'MODIFIER_CITY_OWNER_ATTACH_MODIFIER', 'HD_BEAST_INDUSTRY_BONUS_REQUIREMENTS', 'HD_PLOT_BINARY_COMPRESS_CITY_POSITIVE_AMENITY_' || Exp || '_REQUIREMENTS'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_BEAST_INDUSTRY_CITY_SCIENCE_' || Exp || '_ATTACH', 'ModifierId', 'HD_BEAST_INDUSTRY_CITY_SCIENCE_' || Exp
from HD_Binary_Compress where Exp < 7;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_BEAST_INDUSTRY_CITY_SCIENCE_' || Exp, 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', NULL, NULL
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_BEAST_INDUSTRY_CITY_SCIENCE_' || Exp, 'YieldType', 'YIELD_SCIENCE'
from HD_Binary_Compress where Exp < 7;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_BEAST_INDUSTRY_CITY_SCIENCE_' || Exp, 'Amount', Amount
from HD_Binary_Compress where Exp < 7;

-- 家居行业
insert or ignore into HD_IndustryModifiers (Category, ModifierId) select
	'HOUSEHOLD', 'HD_HOUSEHOLD_INDUSTRY_' || BuildingType
from Buildings where PrereqDistrict in ('DISTRICT_CITY_CENTER', 'DISTRICT_NEIGHBORHOOD') and BuildingType not in (select BuildingType from HD_DUMMY_BUILDINGS);

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_HOUSEHOLD_INDUSTRY_' || BuildingType, 'MODIFIER_BUILDING_YIELD_CHANGE', 'HD_HOUSEHOLD_INDUSTRY_BONUS_REQUIREMENTS', NULL
from Buildings where PrereqDistrict in ('DISTRICT_CITY_CENTER', 'DISTRICT_NEIGHBORHOOD') and BuildingType not in (select BuildingType from HD_DUMMY_BUILDINGS);

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_HOUSEHOLD_INDUSTRY_' || BuildingType, 'BuildingType', BuildingType
from Buildings where PrereqDistrict in ('DISTRICT_CITY_CENTER', 'DISTRICT_NEIGHBORHOOD') and BuildingType not in (select BuildingType from HD_DUMMY_BUILDINGS);

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_HOUSEHOLD_INDUSTRY_' || BuildingType, 'YieldType', 'YIELD_PRODUCTION'
from Buildings where PrereqDistrict in ('DISTRICT_CITY_CENTER', 'DISTRICT_NEIGHBORHOOD') and BuildingType not in (select BuildingType from HD_DUMMY_BUILDINGS);

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_HOUSEHOLD_INDUSTRY_' || BuildingType, 'Amount', 2
from Buildings where PrereqDistrict in ('DISTRICT_CITY_CENTER', 'DISTRICT_NEIGHBORHOOD') and BuildingType not in (select BuildingType from HD_DUMMY_BUILDINGS);

-- =========================
-- 公司效果
-- =========================
insert or ignore into HD_CorporationModifiers (Category, ModifierId) values
	('CROPS',						'HD_CROPS_CORPORATION_CITY_YIELD_BONUS'),
	('AGRICULTURE',			'HD_AGRICULTURE_CORPORATION_IMPROVEMENT_YIELD'),
	('CUISINE',					'HD_CUISINE_CORPORATION_DISTRICT_FOOD'),
	('CUISINE',					'HD_CUISINE_CORPORATION_DISTRICT_CULTURE'),
	('FRUIT',						'HD_FRUIT_CORPORATION_ENVOY_GOLD'),
	('FRUIT',						'HD_FRUIT_CORPORATION_SEA_MOVEMENT'),
	('FRUIT',						'HD_FRUIT_CORPORATION_EMBARKED_MOVEMENT'),
	('BREWING',					'HD_BREWING_CORPORATION_CITY_GROWTH'),
	('BREWING',					'HD_BREWING_CORPORATION_CITY_GOLD'),
	('BEVERAGE',				'HD_BEVERAGE_CORPORATION_GPP'),
	('OIL',							'HD_OIL_CORPORATION_TRADE_FOOD'),
	('OIL',							'HD_OIL_CORPORATION_TRADE_GOLD'),
	('LEATHER',					'HD_LEATHER_CORPORATION_TRADE_PRODUCTION'),
	('LEATHER',					'HD_LEATHER_CORPORATION_TRADE_GOLD'),
	('CLOTH',						'HD_CLOTH_CORPORATION_COMMERCIAL_HUB_REGIONAL_CULTURE'),
	('CLOTH',						'HD_CLOTH_CORPORATION_COMMERCIAL_HUB_REGIONAL_GOLD'),
	('CLOTH',						'HD_CLOTH_CORPORATION_NEIGHBORHOOD_REGIONAL_CULTURE'),
	('CLOTH',						'HD_CLOTH_CORPORATION_NEIGHBORHOOD_REGIONAL_GOLD'),
	('CONSTRUCTION',		'HD_CONSTRUCTION_CORPORATION_DISTRICT_SPEED'),
	('CONSTRUCTION',		'HD_CONSTRUCTION_CORPORATION_BUILDING_SPEED'),
	('CONSTRUCTION',		'HD_CONSTRUCTION_CORPORATION_GPP'),
	('FUEL',						'HD_FUEL_CORPORATION_TIER1_PRODUCTION'),
	('FUEL',						'HD_FUEL_CORPORATION_TIER2_PRODUCTION'),
	('FUEL',						'HD_FUEL_CORPORATION_TIER3_PRODUCTION'),
	('FUEL',						'HD_FUEL_CORPORATION_TIER1_GOLD'),
	('FUEL',						'HD_FUEL_CORPORATION_TIER2_GOLD'),
	('FUEL',						'HD_FUEL_CORPORATION_TIER3_GOLD'),
	('METALLURGY',			'HD_METALLURGY_CORPORATION_SCIENCE'),
	('METALLURGY',			'HD_METALLURGY_CORPORATION_UNIT_STRENGTH'),
	('MINTING',					'HD_MINTING_CORPORATION_TRADE_GOLD'),
	('MINTING',					'HD_MINTING_CORPORATION_GPP'),
	('SEASONING',				'HD_SEASONING_CORPORATION_TRADE_YIELD'),
	('SEAFOOD',					'HD_SEAFOOD_CORPORATION_DISTRICT_FOOD'),
	('SEAFOOD',					'HD_SEAFOOD_CORPORATION_DISTRICT_GOLD'),
	('MARINE_PRODUCTS',	'HD_MARINE_PRODUCTS_CORPORATION_CITY_SCIENCE'),
	('SEA_BEAST',				'HD_SEA_BEAST_CORPORATION_IMPROVEMENT_TOURISM'),
	('SEA_BEAST',				'HD_SEA_BEAST_CORPORATION_WONDER_TOURISM'),
	('SEA_BEAST',				'HD_SEA_BEAST_CORPORATION_NATIONAL_PARK_TOURISM'),
	('CELEBRATION',			'HD_CELEBRATION_CORPORATION_HOLY_SITE'),
	('CELEBRATION',			'HD_CELEBRATION_CORPORATION_TRADE_FAITH'),
	('MEDICINE',				'HD_MEDICINE_CORPORATION_TECH_BOOST'),
	('MEDICINE',				'HD_MEDICINE_CORPORATION_PLAYER_PROPERTY'),
	('MEDICINE',				'HD_MEDICINE_CORPORATION_UNIT_HEAL'),
	('STATIONERY',			'HD_STATIONERY_CORPORATION_PLAYER_PROPERTY'),
	('DECORATION',			'HD_DECORATION_CORPORATION_GREATWORKOBJECT_PRODUCT'),
	('ORNAMENTAL',			'HD_ORNAMENTAL_CORPORATION_IMPROVEMENT_TOURISM'),
	('ORNAMENTAL',			'HD_ORNAMENTAL_CORPORATION_NATIONAL_PARK_TOURISM'),
	('BEAST',						'HD_BEAST_CORPORATION_IMPROVEMENT_TOURISM'),
	('BEAST',						'HD_BEAST_CORPORATION_WONDER_TOURISM'),
	('BEAST',						'HD_BEAST_CORPORATION_NATIONAL_PARK_TOURISM'),
	('HOUSEHOLD',				'HD_HOUSEHOLD_CORPORATION_CHARMING_GOLD'),
	('HOUSEHOLD',				'HD_HOUSEHOLD_CORPORATION_BREATHTAKING_GOLD'),
	('TOYS',						'HD_TOYS_CORPORATION_POP_SCIENCE'),
	('TOYS',						'HD_TOYS_CORPORATION_POP_CULTURE'),
	('COSMETICS',				'HD_COSMETICS_CORPORATION_CIVIC_BOOST'),
	('COSMETICS',				'HD_COSMETICS_CORPORATION_PLAYER_PROPERTY'),
	('COSMETICS',				'HD_COSMETICS_CORPORATION_COMMERCIAL_HUB_CULTURE'),
	('COSMETICS',				'HD_COSMETICS_CORPORATION_COMMERCIAL_HUB_TOURISM'),
	('JEANS',						'HD_JEANS_CORPORATION_IMPROVEMENT_YIELD'),
	('JEANS',						'HD_JEANS_CORPORATION_UNIT_ABILITY'),
	('PERFUME',					'HD_PERFUME_CORPORATION_ALL_YIELD'),
	('PERFUME',					'HD_PERFUME_CORPORATION_GREATWORKOBJECT_PRODUCT'),
	('PERFUME',					'HD_PERFUME_CORPORATION_IMPROVEMENT_TOURISM');

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) values
	('HD_CROPS_CORPORATION_CITY_YIELD_BONUS',										'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',									'HD_CROPS_CORPORATION_BONUS_REQUIREMENTS',					NULL),
	('HD_AGRICULTURE_CORPORATION_IMPROVEMENT_YIELD',						'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',																	'HD_AGRICULTURE_CORPORATION_BONUS_REQUIREMENTS',		'PLOT_HAS_IMPROVEMENT_CLASSIFICATION_AGRICULTURAL_PRODUCTION_REQUIREMENTS'),
	('HD_CUISINE_CORPORATION_DISTRICT_FOOD',										'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',											'HD_CUISINE_CORPORATION_BONUS_REQUIREMENTS',				'DISTRICT_IS_NOT_SPECIALTY_DISTRICT_REQUIREMENTS'),
	('HD_CUISINE_CORPORATION_DISTRICT_CULTURE',									'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',											'HD_CUISINE_CORPORATION_BONUS_REQUIREMENTS',				'DISTRICT_IS_NOT_SPECIALTY_DISTRICT_REQUIREMENTS'),
	('HD_FRUIT_CORPORATION_ENVOY_GOLD',													'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE_PER_USED_INFLUENCE_TOKEN',				'HD_FRUIT_CORPORATION_BONUS_REQUIREMENTS',					NULL),
	('HD_FRUIT_CORPORATION_SEA_MOVEMENT',												'MODIFIER_PLAYER_UNITS_ADJUST_SEA_MOVEMENT',													'HD_FRUIT_CORPORATION_BONUS_REQUIREMENTS',					NULL),
	('HD_FRUIT_CORPORATION_EMBARKED_MOVEMENT',									'MODIFIER_PLAYER_ADJUST_EMBARKED_MOVEMENT',														'HD_FRUIT_CORPORATION_BONUS_REQUIREMENTS',					NULL),
	('HD_BREWING_CORPORATION_CITY_GROWTH',											'MODIFIER_PLAYER_CITIES_ADJUST_CITY_GROWTH',													'HD_BREWING_CORPORATION_BONUS_REQUIREMENTS',				'CITY_HAS_GOVERNOR_REQUIREMENTS'),
	('HD_BREWING_CORPORATION_CITY_GOLD',												'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',									'HD_BREWING_CORPORATION_BONUS_REQUIREMENTS',				'CITY_HAS_GOVERNOR_REQUIREMENTS'),
	('HD_BEVERAGE_CORPORATION_GPP',															'MODIFIER_PLAYER_CITIES_ADJUST_GREAT_PERSON_POINT_BONUS',							'HD_BEVERAGE_CORPORATION_BONUS_REQUIREMENTS',				NULL),
	('HD_OIL_CORPORATION_TRADE_FOOD',														'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',							'HD_OIL_CORPORATION_BONUS_REQUIREMENTS',						NULL),
	('HD_OIL_CORPORATION_TRADE_GOLD',														'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',							'HD_OIL_CORPORATION_BONUS_REQUIREMENTS',						NULL),
	('HD_LEATHER_CORPORATION_TRADE_PRODUCTION',									'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',							'HD_LEATHER_CORPORATION_BONUS_REQUIREMENTS',				NULL),
	('HD_LEATHER_CORPORATION_TRADE_GOLD',												'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',							'HD_LEATHER_CORPORATION_BONUS_REQUIREMENTS',				NULL),
	('HD_CLOTH_CORPORATION_COMMERCIAL_HUB_REGIONAL_CULTURE',		'MODIFIER_PLAYER_CITIES_ADJUST_PROPERTY',															'HD_CLOTH_CORPORATION_BONUS_REQUIREMENTS',					NULL),
	('HD_CLOTH_CORPORATION_COMMERCIAL_HUB_REGIONAL_GOLD',				'MODIFIER_PLAYER_CITIES_ADJUST_PROPERTY',															'HD_CLOTH_CORPORATION_BONUS_REQUIREMENTS',					NULL),
	('HD_CLOTH_CORPORATION_NEIGHBORHOOD_REGIONAL_CULTURE',			'MODIFIER_PLAYER_CITIES_ADJUST_PROPERTY',															'HD_CLOTH_CORPORATION_BONUS_REQUIREMENTS',					NULL),
	('HD_CLOTH_CORPORATION_NEIGHBORHOOD_REGIONAL_GOLD',					'MODIFIER_PLAYER_CITIES_ADJUST_PROPERTY',															'HD_CLOTH_CORPORATION_BONUS_REQUIREMENTS',					NULL),
	('HD_CONSTRUCTION_CORPORATION_DISTRICT_SPEED',							'MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION',							'HD_CONSTRUCTION_CORPORATION_BONUS_REQUIREMENTS',		NULL),
	('HD_CONSTRUCTION_CORPORATION_BUILDING_SPEED',							'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION_MODIFIER',					'HD_CONSTRUCTION_CORPORATION_BONUS_REQUIREMENTS',		NULL),
	('HD_CONSTRUCTION_CORPORATION_GPP',													'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',									'HD_CONSTRUCTION_CORPORATION_BONUS_REQUIREMENTS',		NULL),
	('HD_FUEL_CORPORATION_TIER1_PRODUCTION',										'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',						'HD_FUEL_CORPORATION_BONUS_REQUIREMENTS',						'CITY_HAS_DISTRICT_NEIGHBORHOOD_TIER_1_BUILDING_REQUIREMENTS'),
	('HD_FUEL_CORPORATION_TIER2_PRODUCTION',										'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',						'HD_FUEL_CORPORATION_BONUS_REQUIREMENTS',						'CITY_HAS_DISTRICT_NEIGHBORHOOD_TIER_2_BUILDING_REQUIREMENTS'),
	('HD_FUEL_CORPORATION_TIER3_PRODUCTION',										'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',						'HD_FUEL_CORPORATION_BONUS_REQUIREMENTS',						'CITY_HAS_DISTRICT_NEIGHBORHOOD_TIER_3_BUILDING_REQUIREMENTS'),
	('HD_FUEL_CORPORATION_TIER1_GOLD',													'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',						'HD_FUEL_CORPORATION_BONUS_REQUIREMENTS',						'CITY_HAS_DISTRICT_NEIGHBORHOOD_TIER_1_BUILDING_REQUIREMENTS'),
	('HD_FUEL_CORPORATION_TIER2_GOLD',													'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',						'HD_FUEL_CORPORATION_BONUS_REQUIREMENTS',						'CITY_HAS_DISTRICT_NEIGHBORHOOD_TIER_2_BUILDING_REQUIREMENTS'),
	('HD_FUEL_CORPORATION_TIER3_GOLD',													'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',						'HD_FUEL_CORPORATION_BONUS_REQUIREMENTS',						'CITY_HAS_DISTRICT_NEIGHBORHOOD_TIER_3_BUILDING_REQUIREMENTS'),
	('HD_METALLURGY_CORPORATION_SCIENCE',												'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',									'HD_METALLURGY_CORPORATION_BONUS_REQUIREMENTS',			'HD_CITY_DISTRICT_INDUSTRIAL_ZONE_HAS_6_ADJACENCY_REQUIREMENTS'),
	('HD_METALLURGY_CORPORATION_UNIT_STRENGTH',									'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_STRENGTH',												'HD_METALLURGY_CORPORATION_BONUS_REQUIREMENTS',			NULL),
	('HD_MINTING_CORPORATION_TRADE_GOLD',												'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD',														'HD_MINTING_CORPORATION_BONUS_REQUIREMENTS',				NULL),
	('HD_MINTING_CORPORATION_GPP',															'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',									'HD_MINTING_CORPORATION_BONUS_REQUIREMENTS',				NULL),
	('HD_SEASONING_CORPORATION_TRADE_YIELD',										'MODIFIER_PLAYER_ADJUST_INTERNATIONAL_TRADE_ROUTE_YIELD_MODIFIER',		'HD_SEASONING_CORPORATION_BONUS_REQUIREMENTS',			NULL),
	('HD_SEAFOOD_CORPORATION_DISTRICT_FOOD',										'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',											'HD_SEAFOOD_CORPORATION_BONUS_REQUIREMENTS',				'HD_DISTRICT_IS_OR_ADJACENT_TO_COAST_REQUIREMENTS'),
	('HD_SEAFOOD_CORPORATION_DISTRICT_GOLD',										'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',											'HD_SEAFOOD_CORPORATION_BONUS_REQUIREMENTS',				'HD_DISTRICT_IS_OR_ADJACENT_TO_COAST_REQUIREMENTS'),
	('HD_MARINE_PRODUCTS_CORPORATION_CITY_SCIENCE',							'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',									'HD_MARINE_PRODUCTS_CORPORATION_BONUS_REQUIREMENTS','PLOT_IS_ADJACENT_TO_COAST'),
	('HD_SEA_BEAST_CORPORATION_IMPROVEMENT_TOURISM',						'MODIFIER_PLAYER_CITIES_ADJUST_IMPROVEMENT_TOURISM',									'HD_SEA_BEAST_CORPORATION_BONUS_REQUIREMENTS',			'REQUIRES_CITY_HAS_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_UDMET'),
	('HD_SEA_BEAST_CORPORATION_WONDER_TOURISM',									'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',															'HD_SEA_BEAST_CORPORATION_BONUS_REQUIREMENTS',			'REQUIRES_CITY_HAS_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_UDMET'),
	('HD_SEA_BEAST_CORPORATION_NATIONAL_PARK_TOURISM',					'MODIFIER_PLAYER_CITIES_ADJUST_NATIONAL_PARK_TOURISM',								'HD_SEA_BEAST_CORPORATION_BONUS_REQUIREMENTS',			'REQUIRES_CITY_HAS_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_UDMET'),
	('HD_CELEBRATION_CORPORATION_HOLY_SITE',										'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',										'HD_CELEBRATION_CORPORATION_BONUS_REQUIREMENTS',		'DISTRICT_IS_HOLY_SITE'),
	('HD_CELEBRATION_CORPORATION_TRADE_FAITH',									'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD',														'HD_CELEBRATION_CORPORATION_BONUS_REQUIREMENTS',		NULL),
	('HD_MEDICINE_CORPORATION_TECH_BOOST',											'MODIFIER_PLAYER_ADJUST_TECHNOLOGY_BOOST',														'HD_MEDICINE_CORPORATION_BONUS_REQUIREMENTS',				NULL),
	('HD_MEDICINE_CORPORATION_PLAYER_PROPERTY',									'MODIFIER_PLAYER_ADJUST_PROPERTY',																		'HD_MEDICINE_CORPORATION_BONUS_REQUIREMENTS',				NULL),
	('HD_MEDICINE_CORPORATION_UNIT_HEAL',												'MODIFIER_PLAYER_UNITS_ADJUST_HEAL_PER_TURN',													'HD_MEDICINE_CORPORATION_BONUS_REQUIREMENTS',				NULL),
	('HD_STATIONERY_CORPORATION_PLAYER_PROPERTY',								'MODIFIER_PLAYER_ADJUST_PROPERTY',																		'HD_STATIONERY_CORPORATION_BONUS_REQUIREMENTS',			NULL),
	('HD_DECORATION_CORPORATION_GREATWORKOBJECT_PRODUCT',				'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',															'HD_DECORATION_CORPORATION_BONUS_REQUIREMENTS',			NULL),
	('HD_ORNAMENTAL_CORPORATION_IMPROVEMENT_TOURISM',						'MODIFIER_PLAYER_CITIES_ADJUST_IMPROVEMENT_TOURISM',									'HD_ORNAMENTAL_CORPORATION_BONUS_REQUIREMENTS',			NULL),
	('HD_ORNAMENTAL_CORPORATION_NATIONAL_PARK_TOURISM',					'MODIFIER_PLAYER_ADJUST_TOURISM_FROM_NATIONAL_PARKS',									'HD_ORNAMENTAL_CORPORATION_BONUS_REQUIREMENTS',			NULL),
	('HD_BEAST_CORPORATION_IMPROVEMENT_TOURISM',								'MODIFIER_PLAYER_CITIES_ADJUST_IMPROVEMENT_TOURISM',									'HD_BEAST_CORPORATION_BONUS_REQUIREMENTS',					'REQUIRES_CITY_HAS_DISTRICT_ENTERTAINMENT_COMPLEX_UDMET'),
	('HD_BEAST_CORPORATION_WONDER_TOURISM',											'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',															'HD_BEAST_CORPORATION_BONUS_REQUIREMENTS',					'REQUIRES_CITY_HAS_DISTRICT_ENTERTAINMENT_COMPLEX_UDMET'),
	('HD_BEAST_CORPORATION_NATIONAL_PARK_TOURISM',							'MODIFIER_PLAYER_CITIES_ADJUST_NATIONAL_PARK_TOURISM',								'HD_BEAST_CORPORATION_BONUS_REQUIREMENTS',					'REQUIRES_CITY_HAS_DISTRICT_ENTERTAINMENT_COMPLEX_UDMET'),
	('HD_HOUSEHOLD_CORPORATION_CHARMING_GOLD',									'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',											'HD_HOUSEHOLD_CORPORATION_BONUS_REQUIREMENTS',			'HD_CHARMING_DISTRICT_REQUIREMENTS'),
	('HD_HOUSEHOLD_CORPORATION_BREATHTAKING_GOLD',							'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',											'HD_HOUSEHOLD_CORPORATION_BONUS_REQUIREMENTS',			'HD_BREATHTAKING_DISTRICT_REQUIREMENTS'),
	('HD_TOYS_CORPORATION_POP_SCIENCE',													'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',						'HD_TOYS_CORPORATION_BONUS_REQUIREMENTS',						'CITY_HAS_DISTRICT_NEIGHBORHOOD_TIER_2_BUILDING_REQUIREMENTS'),
	('HD_TOYS_CORPORATION_POP_CULTURE',													'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',						'HD_TOYS_CORPORATION_BONUS_REQUIREMENTS',						'CITY_HAS_DISTRICT_NEIGHBORHOOD_TIER_2_BUILDING_REQUIREMENTS'),
	('HD_COSMETICS_CORPORATION_CIVIC_BOOST',										'MODIFIER_PLAYER_ADJUST_CIVIC_BOOST',																	'HD_COSMETICS_CORPORATION_BONUS_REQUIREMENTS',			NULL),
	('HD_COSMETICS_CORPORATION_PLAYER_PROPERTY',								'MODIFIER_PLAYER_ADJUST_PROPERTY',																		'HD_COSMETICS_CORPORATION_BONUS_REQUIREMENTS',			NULL),
	('HD_COSMETICS_CORPORATION_COMMERCIAL_HUB_CULTURE',					'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',		'HD_COSMETICS_CORPORATION_BONUS_REQUIREMENTS',			'DISTRICT_IS_COMMERCIAL_HUB'),
	('HD_COSMETICS_CORPORATION_COMMERCIAL_HUB_TOURISM',					'MODIFIER_PLAYER_DISTRICTS_ADJUST_TOURISM_ADJACENCY_YIELD_MOFIFIER',	'HD_COSMETICS_CORPORATION_BONUS_REQUIREMENTS',			'DISTRICT_IS_COMMERCIAL_HUB'),
	('HD_JEANS_CORPORATION_IMPROVEMENT_YIELD',									'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',																	'HD_JEANS_CORPORATION_BONUS_REQUIREMENTS',					'PLOT_HAS_IMPROVEMENT_CLASSIFICATION_INDUSTRIAL_PRODUCTION_REQUIREMENTS'),
	('HD_JEANS_CORPORATION_UNIT_ABILITY',												'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',																'HD_JEANS_CORPORATION_BONUS_REQUIREMENTS',					'UNIT_IS_CIVILIAN_CLASS'),
	('HD_PERFUME_CORPORATION_ALL_YIELD',												'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',									'HD_PERFUME_CORPORATION_BONUS_REQUIREMENTS',				NULL),
	('HD_PERFUME_CORPORATION_GREATWORKOBJECT_PRODUCT',					'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',															'HD_PERFUME_CORPORATION_BONUS_REQUIREMENTS',				NULL),
	('HD_PERFUME_CORPORATION_IMPROVEMENT_TOURISM',							'MODIFIER_PLAYER_CITIES_ADJUST_IMPROVEMENT_TOURISM',									'HD_PERFUME_CORPORATION_BONUS_REQUIREMENTS',				NULL);

insert or ignore into ModifierArguments (ModifierId, Name, Value) values
	('HD_CROPS_CORPORATION_CITY_YIELD_BONUS',										'YieldType',								'YIELD_FOOD'),
	('HD_CROPS_CORPORATION_CITY_YIELD_BONUS',  									'Amount',										10),
	('HD_AGRICULTURE_CORPORATION_IMPROVEMENT_YIELD',						'YieldType',								'YIELD_FOOD,YIELD_GOLD'),
	('HD_AGRICULTURE_CORPORATION_IMPROVEMENT_YIELD',  					'Amount',										'2,6'),
	('HD_CUISINE_CORPORATION_DISTRICT_FOOD',										'YieldType',								'YIELD_FOOD'),
	('HD_CUISINE_CORPORATION_DISTRICT_FOOD',  									'Amount',										2),
	('HD_CUISINE_CORPORATION_DISTRICT_CULTURE',									'YieldType',								'YIELD_CULTURE'),
	('HD_CUISINE_CORPORATION_DISTRICT_CULTURE',  								'Amount',										2),
	('HD_FRUIT_CORPORATION_ENVOY_GOLD',													'YieldType',								'YIELD_GOLD'),
	('HD_FRUIT_CORPORATION_ENVOY_GOLD',  												'Amount',										3),
	('HD_FRUIT_CORPORATION_SEA_MOVEMENT',  											'Amount',										1),
	('HD_FRUIT_CORPORATION_EMBARKED_MOVEMENT',  								'Amount',										1),
	('HD_BREWING_CORPORATION_CITY_GROWTH',  										'Amount',										10),
	('HD_BREWING_CORPORATION_CITY_GOLD',												'YieldType',								'YIELD_GOLD'),
	('HD_BREWING_CORPORATION_CITY_GOLD',  											'Amount',										10),
	('HD_BEVERAGE_CORPORATION_GPP',  														'Amount',										25),
	('HD_OIL_CORPORATION_TRADE_FOOD',														'YieldType',								'YIELD_FOOD'),
	('HD_OIL_CORPORATION_TRADE_FOOD',  													'Amount',										4),
	('HD_OIL_CORPORATION_TRADE_GOLD',														'YieldType',								'YIELD_GOLD'),
	('HD_OIL_CORPORATION_TRADE_GOLD',  													'Amount',										6),
	('HD_LEATHER_CORPORATION_TRADE_PRODUCTION',									'YieldType',								'YIELD_PRODUCTION'),
	('HD_LEATHER_CORPORATION_TRADE_PRODUCTION',  								'Amount',										4),
	('HD_LEATHER_CORPORATION_TRADE_GOLD',												'YieldType',								'YIELD_GOLD'),
	('HD_LEATHER_CORPORATION_TRADE_GOLD',  											'Amount',										6),
	('HD_CLOTH_CORPORATION_COMMERCIAL_HUB_REGIONAL_CULTURE',		'Key',											'HD_SINGLE_DISTRICT_PROVIDE_REGIONAL_YIELD_BONUS_DISTRICT_COMMERCIAL_HUB_YIELD_CULTURE'),
	('HD_CLOTH_CORPORATION_COMMERCIAL_HUB_REGIONAL_CULTURE',  	'Amount',										3),
	('HD_CLOTH_CORPORATION_COMMERCIAL_HUB_REGIONAL_GOLD',				'Key',											'HD_SINGLE_DISTRICT_PROVIDE_REGIONAL_YIELD_BONUS_DISTRICT_COMMERCIAL_HUB_YIELD_GOLD'),
	('HD_CLOTH_CORPORATION_COMMERCIAL_HUB_REGIONAL_GOLD',  			'Amount',										6),
	('HD_CLOTH_CORPORATION_NEIGHBORHOOD_REGIONAL_CULTURE',			'Key',											'HD_SINGLE_DISTRICT_PROVIDE_REGIONAL_YIELD_BONUS_DISTRICT_NEIGHBORHOOD_YIELD_CULTURE'),
	('HD_CLOTH_CORPORATION_NEIGHBORHOOD_REGIONAL_CULTURE',  		'Amount',										3),
	('HD_CLOTH_CORPORATION_NEIGHBORHOOD_REGIONAL_GOLD',					'Key',											'HD_SINGLE_DISTRICT_PROVIDE_REGIONAL_YIELD_BONUS_DISTRICT_NEIGHBORHOOD_YIELD_GOLD'),
	('HD_CLOTH_CORPORATION_NEIGHBORHOOD_REGIONAL_GOLD',  				'Amount',										6),
	('HD_CONSTRUCTION_CORPORATION_DISTRICT_SPEED',  						'Amount',										10),
	('HD_CONSTRUCTION_CORPORATION_BUILDING_SPEED',  						'Amount',										10),
	('HD_CONSTRUCTION_CORPORATION_GPP',  												'GreatPersonClassType',			'GREAT_PERSON_CLASS_ENGINEER'),
	('HD_CONSTRUCTION_CORPORATION_GPP',  												'Amount',										50),
	('HD_FUEL_CORPORATION_TIER1_PRODUCTION',										'YieldType',								'YIELD_PRODUCTION'),
	('HD_FUEL_CORPORATION_TIER1_PRODUCTION',  									'Amount',										1),
	('HD_FUEL_CORPORATION_TIER2_PRODUCTION',										'YieldType',								'YIELD_PRODUCTION'),
	('HD_FUEL_CORPORATION_TIER2_PRODUCTION',  									'Amount',										1),
	('HD_FUEL_CORPORATION_TIER3_PRODUCTION',										'YieldType',								'YIELD_PRODUCTION'),
	('HD_FUEL_CORPORATION_TIER3_PRODUCTION',  									'Amount',										1),
	('HD_FUEL_CORPORATION_TIER1_GOLD',													'YieldType',								'YIELD_GOLD'),
	('HD_FUEL_CORPORATION_TIER1_GOLD',  												'Amount',										3),
	('HD_FUEL_CORPORATION_TIER2_GOLD',													'YieldType',								'YIELD_GOLD'),
	('HD_FUEL_CORPORATION_TIER2_GOLD',  												'Amount',										3),
	('HD_FUEL_CORPORATION_TIER3_GOLD',													'YieldType',								'YIELD_GOLD'),
	('HD_FUEL_CORPORATION_TIER3_GOLD',  												'Amount',										3),
	('HD_METALLURGY_CORPORATION_SCIENCE',												'YieldType',								'YIELD_SCIENCE'),
	('HD_METALLURGY_CORPORATION_SCIENCE', 											'Amount',										5),
	('HD_METALLURGY_CORPORATION_UNIT_STRENGTH', 								'Amount',										3),
	('HD_MINTING_CORPORATION_TRADE_GOLD',												'YieldType',								'YIELD_GOLD'),
	('HD_MINTING_CORPORATION_TRADE_GOLD', 											'Amount',										12),
	('HD_MINTING_CORPORATION_GPP',  														'GreatPersonClassType',			'GREAT_PERSON_CLASS_MERCHANT'),
	('HD_MINTING_CORPORATION_GPP',  														'Amount',										50),
	('HD_SEASONING_CORPORATION_TRADE_YIELD',										'YieldType',								'YIELD_PRODUCTION, YIELD_FOOD, YIELD_SCIENCE, YIELD_CULTURE, YIELD_GOLD, YIELD_FAITH'),
	('HD_SEASONING_CORPORATION_TRADE_YIELD',										'Amount',										'20, 20, 20, 20, 20, 20'),
	('HD_SEAFOOD_CORPORATION_DISTRICT_FOOD',										'YieldType',								'YIELD_FOOD'),
	('HD_SEAFOOD_CORPORATION_DISTRICT_FOOD',										'Amount',										1),
	('HD_SEAFOOD_CORPORATION_DISTRICT_GOLD',										'YieldType',								'YIELD_GOLD'),
	('HD_SEAFOOD_CORPORATION_DISTRICT_GOLD',										'Amount',										3),
	('HD_MARINE_PRODUCTS_CORPORATION_CITY_SCIENCE',							'YieldType',								'YIELD_SCIENCE'),
	('HD_MARINE_PRODUCTS_CORPORATION_CITY_SCIENCE',							'Amount',										5),
	('HD_SEA_BEAST_CORPORATION_IMPROVEMENT_TOURISM',						'Amount',										100),
	('HD_SEA_BEAST_CORPORATION_WONDER_TOURISM',									'BoostsWonders',						1),
	('HD_SEA_BEAST_CORPORATION_WONDER_TOURISM',									'ScalingFactor',						200),
	('HD_SEA_BEAST_CORPORATION_NATIONAL_PARK_TOURISM',					'Amount',										100),
	('HD_CELEBRATION_CORPORATION_HOLY_SITE',										'YieldType',								'YIELD_FAITH'),
	('HD_CELEBRATION_CORPORATION_HOLY_SITE',										'Amount',										100),
	('HD_CELEBRATION_CORPORATION_TRADE_FAITH',									'YieldType',								'YIELD_FAITH'),
	('HD_CELEBRATION_CORPORATION_TRADE_FAITH',									'Amount',										3),
	('HD_MEDICINE_CORPORATION_TECH_BOOST',											'Amount',										2),
	('HD_MEDICINE_CORPORATION_PLAYER_PROPERTY',									'Key',											'HD_Player_Extra_Tech_Boost'),
	('HD_MEDICINE_CORPORATION_PLAYER_PROPERTY',									'Amount',										2),
	('HD_MEDICINE_CORPORATION_UNIT_HEAL',												'Type',											'ALL'),
	('HD_MEDICINE_CORPORATION_UNIT_HEAL',												'Amount',										10),
	('HD_STATIONERY_CORPORATION_PLAYER_PROPERTY',								'Key',											'HD_PLAYER_NEED_COUNT_CULTURAL_POLICY'),
	('HD_STATIONERY_CORPORATION_PLAYER_PROPERTY',								'Amount',										1),
	('HD_DECORATION_CORPORATION_GREATWORKOBJECT_PRODUCT',				'GreatWorkObjectType',			'GREATWORKOBJECT_PRODUCT'),
	('HD_DECORATION_CORPORATION_GREATWORKOBJECT_PRODUCT',				'ScalingFactor',						300),
	('HD_ORNAMENTAL_CORPORATION_IMPROVEMENT_TOURISM',						'Amount',										200),
	('HD_ORNAMENTAL_CORPORATION_NATIONAL_PARK_TOURISM',					'Amount',										200),
	('HD_BEAST_CORPORATION_IMPROVEMENT_TOURISM',								'Amount',										100),
	('HD_BEAST_CORPORATION_WONDER_TOURISM',											'BoostsWonders',						1),
	('HD_BEAST_CORPORATION_WONDER_TOURISM',											'ScalingFactor',						200),
	('HD_BEAST_CORPORATION_NATIONAL_PARK_TOURISM',							'Amount',										100),
	('HD_HOUSEHOLD_CORPORATION_CHARMING_GOLD',									'YieldType',								'YIELD_GOLD'),
	('HD_HOUSEHOLD_CORPORATION_CHARMING_GOLD',									'Amount',										6),
	('HD_HOUSEHOLD_CORPORATION_BREATHTAKING_GOLD',							'YieldType',								'YIELD_GOLD'),
	('HD_HOUSEHOLD_CORPORATION_BREATHTAKING_GOLD',							'Amount',										6),
	('HD_TOYS_CORPORATION_POP_SCIENCE',													'YieldType',								'YIELD_SCIENCE'),
	('HD_TOYS_CORPORATION_POP_SCIENCE',													'Amount',										1.5),
	('HD_TOYS_CORPORATION_POP_CULTURE',													'YieldType',								'YIELD_CULTURE'),
	('HD_TOYS_CORPORATION_POP_CULTURE',													'Amount',										1.5),
	('HD_COSMETICS_CORPORATION_CIVIC_BOOST',										'Amount',										5),
	('HD_COSMETICS_CORPORATION_PLAYER_PROPERTY',								'Key',											'HD_Player_Extra_Civic_Boost'),
	('HD_COSMETICS_CORPORATION_PLAYER_PROPERTY',								'Amount',										5),
	('HD_COSMETICS_CORPORATION_COMMERCIAL_HUB_CULTURE',					'YieldTypeToMirror',				'YIELD_GOLD'),
	('HD_COSMETICS_CORPORATION_COMMERCIAL_HUB_CULTURE',					'YieldTypeToGrant',					'YIELD_CULTURE'),
	('HD_COSMETICS_CORPORATION_COMMERCIAL_HUB_TOURISM',					'YieldType',								'YIELD_GOLD'),
	('HD_COSMETICS_CORPORATION_COMMERCIAL_HUB_TOURISM',					'Amount',										100),
	('HD_JEANS_CORPORATION_IMPROVEMENT_YIELD',									'YieldType',								'YIELD_PRODUCTION,YIELD_CULTURE'),
	('HD_JEANS_CORPORATION_IMPROVEMENT_YIELD',  								'Amount',										'4,4'),
	('HD_JEANS_CORPORATION_UNIT_ABILITY',												'AbilityType',							'ABILITY_HD_JEANS_CORPORATION_UNIT'),
	('HD_PERFUME_CORPORATION_ALL_YIELD',												'YieldType',								'YIELD_PRODUCTION,YIELD_FOOD,YIELD_SCIENCE,YIELD_CULTURE,YIELD_GOLD,YIELD_FAITH'),
	('HD_PERFUME_CORPORATION_ALL_YIELD',			  								'Amount',										'10,10,10,10,10,10'),
	('HD_PERFUME_CORPORATION_GREATWORKOBJECT_PRODUCT',					'GreatWorkObjectType',			'GREATWORKOBJECT_PRODUCT'),
	('HD_PERFUME_CORPORATION_GREATWORKOBJECT_PRODUCT',					'ScalingFactor',						600),
	('HD_PERFUME_CORPORATION_IMPROVEMENT_TOURISM',							'Amount',										500);

-- 化学公司
insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'CHEMISTRY', 'HD_CHEMISTRY_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType
from Yields, Districts where DistrictType in ('DISTRICT_CAMPUS', 'DISTRICT_INDUSTRIAL_ZONE');

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_CHEMISTRY_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'MODIFIER_PLAYER_CITIES_ADJUST_PROPERTY', 'HD_CHEMISTRY_CORPORATION_BONUS_REQUIREMENTS', NULL
from Yields, Districts where DistrictType in ('DISTRICT_CAMPUS', 'DISTRICT_INDUSTRIAL_ZONE');

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_CHEMISTRY_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'Key', 'HD_SINGLE_DISTRICT_PROVIDE_REGIONAL_YIELD_SCALING_FACTOR_' || DistrictType || '_' || YieldType
from Yields, Districts where DistrictType in ('DISTRICT_CAMPUS', 'DISTRICT_INDUSTRIAL_ZONE');

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_CHEMISTRY_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'Amount', 50
from Yields, Districts where DistrictType in ('DISTRICT_CAMPUS', 'DISTRICT_INDUSTRIAL_ZONE');

-- 运载公司
insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'TRANSIT', 'HD_TRANSIT_CORPORATION_IMPROVEMENT_ADJACENCY_' || DistrictType || '_ATTACH'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_TRANSIT_CORPORATION_IMPROVEMENT_ADJACENCY_' || DistrictType || '_ATTACH', 'MODIFIER_PLAYER_IMPROVEMENTS_ATTACH_MODIFIER', 'HD_TRANSIT_CORPORATION_BONUS_REQUIREMENTS', 'PLOT_HAS_IMPROVEMENT_CLASSIFICATION_TRANSPORTATION_FACILITIES_REQUIREMENTS'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_TRANSIT_CORPORATION_IMPROVEMENT_ADJACENCY_' || DistrictType || '_ATTACH', 'ModifierId', 'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_1_TILE'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'TRANSIT', 'HD_TRANSIT_CORPORATION_DISTRICT_ADJACENCY_' || DistrictType || '_ATTACH'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_TRANSIT_CORPORATION_DISTRICT_ADJACENCY_' || DistrictType || '_ATTACH', 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER', 'HD_TRANSIT_CORPORATION_BONUS_REQUIREMENTS', 'DISTRICT_IS_DISTRICT_CLASSIFICATION_TRANSPORTATION_FACILITIES_REQUIREMENTS'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_TRANSIT_CORPORATION_DISTRICT_ADJACENCY_' || DistrictType || '_ATTACH', 'ModifierId', 'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_1_TILE'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'TRANSIT', 'HD_TRANSIT_CORPORATION_BUILDING_ADJACENCY_' || DistrictType || '_ATTACH'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_TRANSIT_CORPORATION_BUILDING_ADJACENCY_' || DistrictType || '_ATTACH', 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER', 'HD_TRANSIT_CORPORATION_BONUS_REQUIREMENTS', 'HD_PLOT_HAS_BUILDING_CLASSIFICATION_TRANSPORTATION_FACILITIES_REQUIREMENTS'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_TRANSIT_CORPORATION_BUILDING_ADJACENCY_' || DistrictType || '_ATTACH', 'ModifierId', 'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_1_TILE'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_1_TILE', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_BASE_YIELD_CHANGE', NULL, 'HD_DISTRICT_IS_' || DistrictType || '_ADJACENT'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_1_TILE', 'YieldType', YieldType
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_1_TILE', 'Amount', 1
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

-- 海兽公司
insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'SEA_BEAST', 'HD_SEA_BEAST_CORPORATION_TIER1_ADJACENCY_' || DistrictType || '_ATTACH'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_SEA_BEAST_CORPORATION_TIER1_ADJACENCY_' || DistrictType || '_ATTACH', 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER', 'HD_SEA_BEAST_CORPORATION_BONUS_REQUIREMENTS', 'HD_PLOT_HAS_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_TIER_1_BUILDING_REQUIREMENTS'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_SEA_BEAST_CORPORATION_TIER1_ADJACENCY_' || DistrictType || '_ATTACH', 'ModifierId', 'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_2_TILES'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'SEA_BEAST', 'HD_SEA_BEAST_CORPORATION_TIER2_ADJACENCY_' || DistrictType || '_ATTACH'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_SEA_BEAST_CORPORATION_TIER2_ADJACENCY_' || DistrictType || '_ATTACH', 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER', 'HD_SEA_BEAST_CORPORATION_BONUS_REQUIREMENTS', 'HD_PLOT_HAS_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_TIER_2_BUILDING_REQUIREMENTS'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_SEA_BEAST_CORPORATION_TIER2_ADJACENCY_' || DistrictType || '_ATTACH', 'ModifierId', 'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_2_TILES'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'SEA_BEAST', 'HD_SEA_BEAST_CORPORATION_TIER3_ADJACENCY_' || DistrictType || '_ATTACH'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_SEA_BEAST_CORPORATION_TIER3_ADJACENCY_' || DistrictType || '_ATTACH', 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER', 'HD_SEA_BEAST_CORPORATION_BONUS_REQUIREMENTS', 'HD_PLOT_HAS_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_TIER_3_BUILDING_REQUIREMENTS'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_SEA_BEAST_CORPORATION_TIER3_ADJACENCY_' || DistrictType || '_ATTACH', 'ModifierId', 'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_2_TILES'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_2_TILES', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_BASE_YIELD_CHANGE', NULL, 'HD_DISTRICT_IS_' || DistrictType || '_WITHIN_2_TILES'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_2_TILES', 'YieldType', YieldType
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_' || DistrictType || '_STANDARD_ADJACENCY_WITHIN_2_TILES', 'Amount', 1
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

-- 文具公司
insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'STATIONERY', 'HD_STATIONERY_CORPORATION_CAMPUS_' || Exp || '_ATTACH'
from HD_Binary_Compress where Exp < 5;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_STATIONERY_CORPORATION_CAMPUS_' || Exp || '_ATTACH', 'MODIFIER_PLAYER_CAPITAL_CITY_ATTACH_MODIFIER', 'HD_STATIONERY_CORPORATION_BONUS_REQUIREMENTS', 'HD_PLOT_BINARY_COMPRESS_PLAYER_CULTURAL_POLICY_' || Exp || '_REQUIREMENTS'
from HD_Binary_Compress where Exp < 5;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_STATIONERY_CORPORATION_CAMPUS_' || Exp || '_ATTACH', 'ModifierId', 'HD_STATIONERY_CORPORATION_CAMPUS_' || Exp
from HD_Binary_Compress where Exp < 5;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_STATIONERY_CORPORATION_CAMPUS_' || Exp, 'MODIFIER_PLAYER_DISTRICTS_ADJUST_BASE_YIELD_CHANGE', NULL, 'DISTRICT_IS_CAMPUS'
from HD_Binary_Compress where Exp < 5;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_STATIONERY_CORPORATION_CAMPUS_' || Exp, 'YieldType', 'YIELD_SCIENCE'
from HD_Binary_Compress where Exp < 5;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_STATIONERY_CORPORATION_CAMPUS_' || Exp, 'Amount', Amount
from HD_Binary_Compress where Exp < 5;

insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'STATIONERY', 'HD_STATIONERY_CORPORATION_THEATER_' || Exp || '_ATTACH'
from HD_Binary_Compress where Exp < 5;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_STATIONERY_CORPORATION_THEATER_' || Exp || '_ATTACH', 'MODIFIER_PLAYER_CAPITAL_CITY_ATTACH_MODIFIER', 'HD_STATIONERY_CORPORATION_BONUS_REQUIREMENTS', 'HD_PLOT_BINARY_COMPRESS_PLAYER_CULTURAL_POLICY_' || Exp || '_REQUIREMENTS'
from HD_Binary_Compress where Exp < 5;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_STATIONERY_CORPORATION_THEATER_' || Exp || '_ATTACH', 'ModifierId', 'HD_STATIONERY_CORPORATION_THEATER_' || Exp
from HD_Binary_Compress where Exp < 5;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_STATIONERY_CORPORATION_THEATER_' || Exp, 'MODIFIER_PLAYER_DISTRICTS_ADJUST_BASE_YIELD_CHANGE', NULL, 'DISTRICT_IS_THEATER'
from HD_Binary_Compress where Exp < 5;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_STATIONERY_CORPORATION_THEATER_' || Exp, 'YieldType', 'YIELD_CULTURE'
from HD_Binary_Compress where Exp < 5;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_STATIONERY_CORPORATION_THEATER_' || Exp, 'Amount', Amount
from HD_Binary_Compress where Exp < 5;

-- 艺术公司
insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'ART', 'HD_ART_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType
from Yields, Districts where DistrictType in ('DISTRICT_HOLY_SITE', 'DISTRICT_THEATER');

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_ART_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'MODIFIER_PLAYER_CITIES_ADJUST_PROPERTY', 'HD_ART_CORPORATION_BONUS_REQUIREMENTS', NULL
from Yields, Districts where DistrictType in ('DISTRICT_HOLY_SITE', 'DISTRICT_THEATER');

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_ART_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'Key', 'HD_SINGLE_DISTRICT_PROVIDE_REGIONAL_YIELD_SCALING_FACTOR_' || DistrictType || '_' || YieldType
from Yields, Districts where DistrictType in ('DISTRICT_HOLY_SITE', 'DISTRICT_THEATER');

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_ART_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'Amount', 50
from Yields, Districts where DistrictType in ('DISTRICT_HOLY_SITE', 'DISTRICT_THEATER');

insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'ART', 'HD_ART_CORPORATION_' || GreatWorkObjectType
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_ART_CORPORATION_' || GreatWorkObjectType, 'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM', 'HD_ART_CORPORATION_BONUS_REQUIREMENTS', NULL
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_ART_CORPORATION_' || GreatWorkObjectType, 'GreatWorkObjectType', GreatWorkObjectType
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_ART_CORPORATION_' || GreatWorkObjectType, 'ScalingFactor', 300
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

-- 饰品公司
insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'DECORATION', 'HD_DECORATION_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType
from Yields, Districts where DistrictType in ('DISTRICT_COMMERCIAL_HUB', 'DISTRICT_NEIGHBORHOOD');

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_DECORATION_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'MODIFIER_PLAYER_CITIES_ADJUST_PROPERTY', 'HD_DECORATION_CORPORATION_BONUS_REQUIREMENTS', NULL
from Yields, Districts where DistrictType in ('DISTRICT_COMMERCIAL_HUB', 'DISTRICT_NEIGHBORHOOD');

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_DECORATION_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'Key', 'HD_SINGLE_DISTRICT_PROVIDE_REGIONAL_YIELD_SCALING_FACTOR_' || DistrictType || '_' || YieldType
from Yields, Districts where DistrictType in ('DISTRICT_COMMERCIAL_HUB', 'DISTRICT_NEIGHBORHOOD');

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_DECORATION_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'Amount', 50
from Yields, Districts where DistrictType in ('DISTRICT_COMMERCIAL_HUB', 'DISTRICT_NEIGHBORHOOD');

-- 花木公司
insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'ORNAMENTAL', 'HD_ORNAMENTAL_CORPORATION_' || DistrictType
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_ORNAMENTAL_CORPORATION_' || DistrictType, 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER', 'HD_ORNAMENTAL_CORPORATION_BONUS_REQUIREMENTS', 'DISTRICT_IS_' || DistrictType || '_ADJACENT_TO_IMPROVEMENT_CLASSIFICATION_TOURISM_FACILITIES_REQUIREMENTS'
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_ORNAMENTAL_CORPORATION_' || DistrictType, 'YieldType', YieldType
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_ORNAMENTAL_CORPORATION_' || DistrictType, 'Amount', 50
from DistrictCorrespondingYieldType_HD where HasAdjacency = 1;

-- 珍兽公司
insert or ignore into HD_CorporationModifiers (Category, ModifierId) select
	'BEAST', 'HD_BEAST_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType
from Yields, Districts where DistrictType in ('DISTRICT_ENTERTAINMENT_COMPLEX', 'DISTRICT_WONDER');

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
	'HD_BEAST_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'MODIFIER_PLAYER_CITIES_ADJUST_PROPERTY', 'HD_BEAST_CORPORATION_BONUS_REQUIREMENTS', NULL
from Yields, Districts where DistrictType in ('DISTRICT_ENTERTAINMENT_COMPLEX', 'DISTRICT_WONDER');

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_BEAST_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'Key', 'HD_SINGLE_DISTRICT_PROVIDE_REGIONAL_YIELD_SCALING_FACTOR_' || DistrictType || '_' || YieldType
from Yields, Districts where DistrictType in ('DISTRICT_ENTERTAINMENT_COMPLEX', 'DISTRICT_WONDER');

insert or ignore into ModifierArguments (ModifierId, Name, Value) select
	'HD_BEAST_CORPORATION_' || DistrictType || '_REGIONAL_' || YieldType, 'Amount', 50
from Yields, Districts where DistrictType in ('DISTRICT_ENTERTAINMENT_COMPLEX', 'DISTRICT_WONDER');

-- 文本
insert or ignore into ModifierStrings (ModifierId, Context, Text) values
	('HD_METALLURGY_CORPORATION_UNIT_STRENGTH', 'Preview', 'LOC_HD_METALLURGY_CORPORATION_UNIT_STRENGTH_TEXT');

-- 能力
insert or ignore into Types (Type, Kind) values
  ('ABILITY_HD_JEANS_CORPORATION_UNIT', 'KIND_ABILITY');

insert or replace into UnitAbilities (UnitAbilityType, Name, Description, Inactive) values
	('ABILITY_HD_JEANS_CORPORATION_UNIT', 'LOC_ABILITY_HD_JEANS_CORPORATION_UNIT_NAME', 'LOC_ABILITY_HD_JEANS_CORPORATION_UNIT_DESCRIPTION', 1);

insert or replace into UnitAbilityModifiers (UnitAbilityType, ModifierId) values
  ('ABILITY_HD_JEANS_CORPORATION_UNIT', 'HD_JEANS_CORPORATION_UNIT_IGNORE_TERRAIN'),
  ('ABILITY_HD_JEANS_CORPORATION_UNIT', 'HD_JEANS_CORPORATION_UNIT_IGNORE_RIVERS'),
  ('ABILITY_HD_JEANS_CORPORATION_UNIT', 'HD_JEANS_CORPORATION_UNIT_IGNORE_SHORES');

insert or replace into Modifiers (ModifierId, ModifierType) values
	('HD_JEANS_CORPORATION_UNIT_IGNORE_TERRAIN', 	'MODIFIER_PLAYER_UNIT_ADJUST_IGNORE_TERRAIN_COST'),
	('HD_JEANS_CORPORATION_UNIT_IGNORE_RIVERS', 	'MODIFIER_PLAYER_UNIT_ADJUST_IGNORE_RIVERS'),
	('HD_JEANS_CORPORATION_UNIT_IGNORE_SHORES', 	'MODIFIER_PLAYER_UNIT_ADJUST_IGNORE_SHORES');

insert or replace into ModifierArguments (ModifierId, Name, Value) values
	('HD_JEANS_CORPORATION_UNIT_IGNORE_TERRAIN',	'Type',		'ALL'),
	('HD_JEANS_CORPORATION_UNIT_IGNORE_TERRAIN',	'Ignore',	1),
	('HD_JEANS_CORPORATION_UNIT_IGNORE_RIVERS',		'Ignore',	1),
	('HD_JEANS_CORPORATION_UNIT_IGNORE_SHORES',		'Ignore',	1);

insert or replace into TypeTags (Type, Tag) values
	('ABILITY_HD_JEANS_CORPORATION_UNIT', 'CLASS_LANDCIVILIAN');

-- =====================================================================================================================================
-- 行业公司文本描述
	-- 实际上这两张表在HD体系已经被弃用了，因为HD的绝大部分资源的行业公司有两种特效
	-- 这里填一下只是为了防止潜在的兼容性问题
-- =====================================================================================================================================
delete from ResourceIndustries;
delete from ResourceCorporations;

insert or ignore into ResourceIndustries (ResourceType, ResourceEffect, ResourceEffectTExt) select
	a.ResourceType,
	b.IndustryEffect,
	'LOC_' || b.IndustryEffect || '_DESCRIPTION'
from HD_Monopoly_Resource_Categories a inner join HD_Monopoly_Categories b on a.Category = b.Category where b.IndustryEffect is not NULL;

insert or ignore into ResourceCorporations (ResourceType, ResourceEffect, ResourceEffectTExt) select
	a.ResourceType,
	b.CorporationEffect,
	'LOC_' || b.CorporationEffect || '_DESCRIPTION'
from HD_Monopoly_Resource_Categories a inner join HD_Monopoly_Categories b on a.Category = b.Category where b.CorporationEffect is not NULL;

-- =====================================================================================================================================
-- 火车站
-- =====================================================================================================================================
insert or ignore into ImprovementModifiers (ImprovementType, ModifierId) values
	('IMPROVEMENT_LEU_STATION', 'LEU_STATION_PRODUCT_TOURISM_COMMERCIAL_HUB'),
	('IMPROVEMENT_LEU_STATION', 'LEU_STATION_PRODUCT_TOURISM_HARBOR');

insert or ignore into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) values
	('LEU_STATION_PRODUCT_TOURISM_COMMERCIAL_HUB',	'MODIFIER_SINGLE_CITY_ADJUST_TOURISM',	'PLOT_ADJACENT_TO_DISTRICT_COMMERCIAL_HUB_REQUIREMENTS'),
	('LEU_STATION_PRODUCT_TOURISM_HARBOR',					'MODIFIER_SINGLE_CITY_ADJUST_TOURISM',	'PLOT_ADJACENT_TO_DISTRICT_HARBOR_REQUIREMENTS');

insert or ignore into ModifierArguments (ModifierId, Name, Value) values
	('LEU_STATION_PRODUCT_TOURISM_COMMERCIAL_HUB',	'GreatWorkObjectType',	'GREATWORKOBJECT_PRODUCT'),
	('LEU_STATION_PRODUCT_TOURISM_COMMERCIAL_HUB',	'ScalingFactor',				150),
	('LEU_STATION_PRODUCT_TOURISM_HARBOR',					'GreatWorkObjectType',	'GREATWORKOBJECT_PRODUCT'),
	('LEU_STATION_PRODUCT_TOURISM_HARBOR',					'ScalingFactor',				150);

-- =====================================================================================================================================
-- 仓库和埠头
-- =====================================================================================================================================
update Improvements set
	PrereqTech = 'TECH_APPRENTICESHIP',
	RequiresAdjacentBonusOrLuxury = 1,
	RequiresAdjacentLuxury = 0,
	Removable = 1,
	OnlyOpenBorders = 0,
	OnePerCity = 1,
	Capturable = 1
where ImprovementType in ('IMPROVEMENT_LEU_WAREHOUSE', 'IMPROVEMENT_LEU_CONTAINER_PORT');

delete from TraitModifiers where ModifierId in (
	'LEU_WAREHOUSE_TRADE_GOLD',
	'LEU_WAREHOUSE_TRADE_PRODUCTION',
	'LEU_CONTAINER_PORT_TRADE_GOLD',
	'LEU_CONTAINER_PORT_TRADE_PRODUCTION'
) and TraitType = 'TRAIT_LEADER_MAJOR_CIV';

delete from ImprovementModifiers where ModifierId in (
	'LEU_WAREHOUSE_CORPORATION_TRADE_GOLD',
	'LEU_WAREHOUSE_CORPORATION_TRADE_PRODUCTION',
	'LEU_CONTAINER_PORT_CORPORATION_TRADE_GOLD',
	'LEU_CONTAINER_PORT_CORPORATION_TRADE_PRODUCTION'
) and ImprovementType = 'IMPROVEMENT_CORPORATION';

insert or replace into Improvement_ValidFeatures (ImprovementType, FeatureType) select
	'IMPROVEMENT_LEU_WAREHOUSE', FeatureType
from Features where FeatureType in (
	'FEATURE_JUNGLE', 'FEATURE_FOREST', 'FEATURE_JNR_SAVANNAH'
);

insert or replace into Improvement_ValidFeatures (ImprovementType, FeatureType) select
	'IMPROVEMENT_LEU_CONTAINER_PORT', FeatureType
from Features where FeatureType in (
	'FEATURE_REEF', 'FEATURE_SUK_KELP'
);

delete from ImprovementModifiers where ModifierId like 'LEU_INVESTOR_CORPORATION_BOOST_%';

update Improvement_ValidBuildUnits set UnitType = 'UNIT_LEU_TYCOON' where
	ImprovementType in ('IMPROVEMENT_LEU_WAREHOUSE', 'IMPROVEMENT_LEU_CONTAINER_PORT');

update Improvement_YieldChanges set YieldChange = 6 where YieldType = 'YIELD_PRODUCTION' and
	ImprovementType in ('IMPROVEMENT_LEU_WAREHOUSE', 'IMPROVEMENT_LEU_CONTAINER_PORT');
update Improvement_YieldChanges set YieldChange = 6 where YieldType = 'YIELD_GOLD' and
	ImprovementType in ('IMPROVEMENT_LEU_WAREHOUSE', 'IMPROVEMENT_LEU_CONTAINER_PORT');

delete from Improvement_BonusYieldChanges where ImprovementType in ('IMPROVEMENT_LEU_WAREHOUSE', 'IMPROVEMENT_LEU_CONTAINER_PORT');

insert or replace into Improvement_YieldChanges (ImprovementType, YieldType, YieldChange) values
	('IMPROVEMENT_LEU_WAREHOUSE',					'YIELD_FOOD',		0),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'YIELD_FOOD',		0);

insert or replace into Improvement_Adjacencies (ImprovementType, YieldChangeId) values
	('IMPROVEMENT_LEU_WAREHOUSE',		'HD_WAREHOUSE_BONUS_FOOD'),
	('IMPROVEMENT_LEU_WAREHOUSE',		'HD_WAREHOUSE_LUXURY_GOLD'),
	('IMPROVEMENT_LEU_WAREHOUSE',		'HD_WAREHOUSE_STRATEGIC_PRODUCTION'),
	('IMPROVEMENT_LEU_WAREHOUSE',		'HD_WAREHOUSE_CANAL_GOLD'),
	('IMPROVEMENT_LEU_WAREHOUSE',		'HD_WAREHOUSE_AERODROME_PRODUCTION'),
	('IMPROVEMENT_LEU_WAREHOUSE',		'HD_WAREHOUSE_MOUNTAIN_TUNNEL_GOLD'),
	('IMPROVEMENT_LEU_WAREHOUSE',		'HD_WAREHOUSE_INDUSTRY_PRODUCTION'),
	('IMPROVEMENT_LEU_WAREHOUSE',		'HD_WAREHOUSE_CORPORATION_GOLD'),
	('IMPROVEMENT_LEU_WAREHOUSE',		'HD_WAREHOUSE_STATION_PRODUCTION'),

	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_BONUS_FOOD'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_LUXURY_GOLD'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_STRATEGIC_PRODUCTION'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_CANAL_GOLD'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_AERODROME_PRODUCTION'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_MOUNTAIN_TUNNEL_GOLD'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_INDUSTRY_PRODUCTION'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_CORPORATION_GOLD'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_STATION_PRODUCTION');

insert or replace into Adjacency_YieldChanges (ID, Description, YieldType, YieldChange, AdjacentResourceClass) values
	('HD_WAREHOUSE_BONUS_FOOD', 								'Placeholder',	'YIELD_FOOD',				2,						'RESOURCECLASS_BONUS'),
	('HD_CONTAINER_PORT_BONUS_FOOD',  					'Placeholder',	'YIELD_FOOD',				2,						'RESOURCECLASS_BONUS'),
	('HD_WAREHOUSE_LUXURY_GOLD', 								'Placeholder',	'YIELD_GOLD',				3,						'RESOURCECLASS_LUXURY'),
	('HD_CONTAINER_PORT_LUXURY_GOLD', 					'Placeholder',	'YIELD_GOLD',				3,						'RESOURCECLASS_LUXURY'),
	('HD_WAREHOUSE_STRATEGIC_PRODUCTION', 			'Placeholder',	'YIELD_PRODUCTION',	2,						'RESOURCECLASS_STRATEGIC'),
	('HD_CONTAINER_PORT_STRATEGIC_PRODUCTION', 	'Placeholder',	'YIELD_PRODUCTION',	2,						'RESOURCECLASS_STRATEGIC');

insert or replace into Adjacency_YieldChanges (ID, Description, YieldType, YieldChange, AdjacentDistrict) values
	('HD_WAREHOUSE_CANAL_GOLD',									'Placeholder',	'YIELD_GOLD',					3,						'DISTRICT_CANAL'),
	('HD_CONTAINER_PORT_CANAL_GOLD',						'Placeholder',	'YIELD_GOLD',					3,						'DISTRICT_CANAL'),
	('HD_WAREHOUSE_AERODROME_PRODUCTION',				'Placeholder',	'YIELD_PRODUCTION',		2,						'DISTRICT_AERODROME'),
	('HD_CONTAINER_PORT_AERODROME_PRODUCTION',	'Placeholder',	'YIELD_PRODUCTION',		2,						'DISTRICT_AERODROME');

insert or replace into Adjacency_YieldChanges (ID, Description, YieldType, YieldChange, AdjacentImprovement) values
	('HD_WAREHOUSE_MOUNTAIN_TUNNEL_GOLD',					'Placeholder',	'YIELD_GOLD',				3,						'IMPROVEMENT_MOUNTAIN_TUNNEL'),
	('HD_CONTAINER_PORT_MOUNTAIN_TUNNEL_GOLD',		'Placeholder',	'YIELD_GOLD',				3,						'IMPROVEMENT_MOUNTAIN_TUNNEL'),
	('HD_WAREHOUSE_INDUSTRY_PRODUCTION',					'Placeholder',	'YIELD_PRODUCTION',	1,						'IMPROVEMENT_INDUSTRY'),
	('HD_CONTAINER_PORT_INDUSTRY_PRODUCTION',			'Placeholder',	'YIELD_PRODUCTION',	1,						'IMPROVEMENT_INDUSTRY'),
	('HD_WAREHOUSE_CORPORATION_GOLD',    					'Placeholder',	'YIELD_GOLD',				3,						'IMPROVEMENT_CORPORATION'),
	('HD_CONTAINER_PORT_CORPORATION_GOLD',    		'Placeholder',	'YIELD_GOLD',				3,						'IMPROVEMENT_CORPORATION'),
	('HD_WAREHOUSE_STATION_PRODUCTION',						'Placeholder',	'YIELD_PRODUCTION',	2,						'IMPROVEMENT_LEU_STATION'),
	('HD_CONTAINER_PORT_STATION_PRODUCTION',			'Placeholder',	'YIELD_PRODUCTION',	2,						'IMPROVEMENT_LEU_STATION');
	
insert or replace into ImprovementModifiers (ImprovementType, ModifierId) values
	('IMPROVEMENT_LEU_WAREHOUSE',					'HD_WAREHOUSE_TRADE_BONUS'),
	('IMPROVEMENT_LEU_WAREHOUSE',					'HD_WAREHOUSE_PRODUCT_TOURISM'),
	('IMPROVEMENT_LEU_WAREHOUSE',					'HD_WAREHOUSE_PLOT_YIELD_BONUS'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_TRADE_BONUS'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_WAREHOUSE_PRODUCT_TOURISM'),
	('IMPROVEMENT_LEU_CONTAINER_PORT',		'HD_CONTAINER_PORT_PLOT_YIELD_BONUS');

insert or replace into Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) values
	('HD_WAREHOUSE_TRADE_BONUS',							'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD',		null),
	('HD_CONTAINER_PORT_TRADE_BONUS',					'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD',		null),
	('HD_WAREHOUSE_PRODUCT_TOURISM',					'MODIFIER_SINGLE_CITY_ADJUST_TOURISM',				null),
	('HD_WAREHOUSE_PLOT_YIELD_BONUS',					'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					'HD_PLOT_HAS_INDUSTRY_OR_CORPORATION_REQUIRMENTS'),
	('HD_CONTAINER_PORT_PLOT_YIELD_BONUS',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					'HD_PLOT_HAS_INDUSTRY_OR_CORPORATION_REQUIRMENTS');

insert or replace into ModifierArguments (ModifierId, Name, Value) values
	('HD_WAREHOUSE_TRADE_BONUS',						'YieldType',						'YIELD_PRODUCTION'),
	('HD_WAREHOUSE_TRADE_BONUS',						'Amount',								1),
	('HD_CONTAINER_PORT_TRADE_BONUS',				'YieldType',						'YIELD_GOLD'),
	('HD_CONTAINER_PORT_TRADE_BONUS',				'Amount',								3),
	('HD_WAREHOUSE_PRODUCT_TOURISM',				'GreatWorkObjectType',	'GREATWORKOBJECT_PRODUCT'),
	('HD_WAREHOUSE_PRODUCT_TOURISM',				'ScalingFactor',				150),
	('HD_WAREHOUSE_PLOT_YIELD_BONUS',				'YieldType',						'YIELD_PRODUCTION'),
	('HD_WAREHOUSE_PLOT_YIELD_BONUS',				'Amount',								1),
	('HD_CONTAINER_PORT_PLOT_YIELD_BONUS',	'YieldType',						'YIELD_GOLD'),
	('HD_CONTAINER_PORT_PLOT_YIELD_BONUS',	'Amount',								3);

-- =====================================================================================================================================
-- 跨国公司
-- =====================================================================================================================================
update Improvements set PrereqTech = null, PrereqCivic = 'CIVIC_CAPITALISM' where ImprovementType = 'IMPROVEMENT_LEU_TRANSNATIONAL';
update Improvements set PrereqTech = null, PrereqCivic = 'CIVIC_CAPITALISM' where ImprovementType = 'IMPROVEMENT_LEU_TRANSNATIONAL_SEA';
delete from Improvement_BonusYieldChanges where Id = 553;
delete from Improvement_BonusYieldChanges where Id = 554;

update Improvements set PrereqTech = null, PrereqCivic = 'CIVIC_NEOCOLONIALISM_HD' where ImprovementType = 'IMPROVEMENT_LEU_TRANSNATIONAL'
	and exists (select CivicType from Civics where CivicType = 'CIVIC_NEOCOLONIALISM_HD');
update Improvements set PrereqTech = null, PrereqCivic = 'CIVIC_NEOCOLONIALISM_HD' where ImprovementType = 'IMPROVEMENT_LEU_TRANSNATIONAL_SEA'
	and exists (select CivicType from Civics where CivicType = 'CIVIC_NEOCOLONIALISM_HD');

-- =====================================================================================================================================
-- 尤里卡
-- =====================================================================================================================================
-- 阶级斗争
update Boosts set BoostClass = 'BOOST_TRIGGER_NONE_LATE_GAME_CRITICAL_TECH', BuildingType = null, NumItems = 0,
	TriggerDescription = 'LOC_BOOST_TRIGGER_CLASS_STRUGGLE_HD_MONO', TriggerLongDescription = 'LOC_BOOST_TRIGGER_LONGDESC_CLASS_STRUGGLE_HD_MONO'
where CivicType = 'CIVIC_CLASS_STRUGGLE';

insert or replace into GlobalParameters (Name, Value) values
	('HD_CLASS_STRUGGLE_BOOST_WAREHOUSE',  1);

-- 宏观调控
update Boosts set BoostClass = 'BOOST_TRIGGER_HAVE_X_IMPROVEMENTS', BuildingType = null, TriggerDescription = 'LOC_BOOST_TRIGGER_CAPITALISM_HD', NumItems = 1,
	TriggerLongDescription = 'LOC_BOOST_TRIGGER_LONGDESC_CAPITALISM_HD', ImprovementType = 'IMPROVEMENT_CORPORATION'
where CivicType = 'CIVIC_CAPITALISM';

-- =====================================================================================================================================
-- 城堡庄园
-- =====================================================================================================================================
update Improvements set
	PrereqCivic = 'CIVIC_FEUDALISM',
	RequiresAdjacentBonusOrLuxury = 0,
	Description = 'LOC_IMPROVEMENT_CHATEAU_DESCRIPTION_MONOPOLIES'
where ImprovementType = 'IMPROVEMENT_CHATEAU';

insert or replace into Improvement_YieldChanges (ImprovementType, YieldType, YieldChange) values
	('IMPROVEMENT_CHATEAU', 'YIELD_PRODUCTION', 0);

delete from Improvement_Adjacencies where ImprovementType = 'IMPROVEMENT_CHATEAU' and YieldChangeId in ('Chateau_Bonus_Food', 'Chateau_Luxury_Culture');

insert or replace into Improvement_Adjacencies (ImprovementType, YieldChangeId) values
	('IMPROVEMENT_CHATEAU', 'HD_Chateau_Monopoly_District_Food'),
	('IMPROVEMENT_CHATEAU', 'HD_Chateau_Monopoly_District_Production');

insert or replace into Adjacency_YieldChanges (ID, Description, YieldType, YieldChange, OtherDistrictAdjacent, AdjacentWonder) values
	('HD_Chateau_Monopoly_District_Food',				'Placeholder', 'YIELD_FOOD',				1, 1, 0),
	('HD_Chateau_Monopoly_District_Production',	'Placeholder', 'YIELD_PRODUCTION',	1, 1, 0);