insert or ignore into Types (Type, Kind) values
	('POLICY_WAREHOUSE_MANAGEMENT',		'KIND_POLICY'),
	('POLICY_AUTO_STEREO_WAREHOUSE',	'KIND_POLICY');

insert or replace into Policies (PolicyType, Name, Description, PrereqCivic, PrereqTech, GovernmentSlotType) values
	('POLICY_WAREHOUSE_MANAGEMENT',		'LOC_POLICY_WAREHOUSE_MANAGEMENT_NAME',			'LOC_POLICY_WAREHOUSE_MANAGEMENT_DESCRIPTION',		null,		'TECH_INDUSTRIALIZATION',	        'SLOT_ECONOMIC'),
	('POLICY_AUTO_STEREO_WAREHOUSE',	'LOC_POLICY_AUTO_STEREO_WAREHOUSE_NAME',		'LOC_POLICY_AUTO_STEREO_WAREHOUSE_DESCRIPTION',		null,		'TECH_INDUSTRIAL_AUTOMATION_HD',	'SLOT_ECONOMIC');

insert or replace into ObsoletePolicies (PolicyType, ObsoletePolicy) values
	('POLICY_WAREHOUSE_MANAGEMENT',		'POLICY_AUTO_STEREO_WAREHOUSE');

update ModifierArguments set Value = 4 where Name = 'Amount' and ModifierId = 'ECOMMERCE_TRADEROUTEPRODUCTION';
update ModifierArguments set Value = 15 where Name = 'Amount' and ModifierId = 'ECOMMERCE_TRADEROUTEGOLD';

insert or replace into PolicyModifiers (PolicyType, ModifierId) values
	('POLICY_ECOMMERCE',	            'ECOMMERCE_PRODUCT_TOURISM'),
	('POLICY_ECOMMERCE',	            'ECOMMERCE_PRODUCT_TOURISM_POWERED'),
	('POLICY_WAREHOUSE_MANAGEMENT',	  'WAREHOUSE_MANAGEMENT_COMMERCIAL_HUB_BONUS'),
	('POLICY_WAREHOUSE_MANAGEMENT',	  'WAREHOUSE_MANAGEMENT_HARBOR_BONUS'),
	('POLICY_WAREHOUSE_MANAGEMENT',	  'WAREHOUSE_MANAGEMENT_INDUSTRIAL_ZONE_BONUS'),
	('POLICY_AUTO_STEREO_WAREHOUSE',	'AUTO_STEREO_WAREHOUSE_COMMERCIAL_HUB_BONUS'),
	('POLICY_AUTO_STEREO_WAREHOUSE',	'AUTO_STEREO_WAREHOUSE_HARBOR_BONUS'),
	('POLICY_AUTO_STEREO_WAREHOUSE',	'AUTO_STEREO_WAREHOUSE_INDUSTRIAL_ZONE_BONUS');

insert or replace into Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) values
	('ECOMMERCE_PRODUCT_TOURISM',			                'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',	          NULL),
	('ECOMMERCE_PRODUCT_TOURISM_POWERED',	            'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',	          'CITY_IS_POWERED'),
	('WAREHOUSE_MANAGEMENT_COMMERCIAL_HUB_BONUS',		  'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',	'HD_WAREHOUSE_MANAGEMENT_COMMERCIAL_HUB_REQUIRMENTS'),
	('WAREHOUSE_MANAGEMENT_HARBOR_BONUS',						  'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',	'HD_WAREHOUSE_MANAGEMENT_HARBOR_REQUIRMENTS'),
	('WAREHOUSE_MANAGEMENT_INDUSTRIAL_ZONE_BONUS',	  'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',	'HD_WAREHOUSE_MANAGEMENT_INDUSTRIAL_ZONE_REQUIRMENTS'),
	('AUTO_STEREO_WAREHOUSE_COMMERCIAL_HUB_BONUS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',	'HD_WAREHOUSE_MANAGEMENT_COMMERCIAL_HUB_REQUIRMENTS'),
	('AUTO_STEREO_WAREHOUSE_HARBOR_BONUS',						'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',	'HD_WAREHOUSE_MANAGEMENT_HARBOR_REQUIRMENTS'),
	('AUTO_STEREO_WAREHOUSE_INDUSTRIAL_ZONE_BONUS',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',	'HD_WAREHOUSE_MANAGEMENT_INDUSTRIAL_ZONE_REQUIRMENTS');

insert or replace into ModifierArguments (ModifierId, Name, Value) values
	('ECOMMERCE_PRODUCT_TOURISM',			                'GreatWorkObjectType',	'GREATWORKOBJECT_PRODUCT'),
	('ECOMMERCE_PRODUCT_TOURISM',			                'ScalingFactor',			  300),
	('ECOMMERCE_PRODUCT_TOURISM_POWERED',	            'GreatWorkObjectType',	'GREATWORKOBJECT_PRODUCT'),
	('ECOMMERCE_PRODUCT_TOURISM_POWERED',	            'ScalingFactor',			  300),
	('WAREHOUSE_MANAGEMENT_COMMERCIAL_HUB_BONUS',		  'YieldType',	          'YIELD_GOLD'),
	('WAREHOUSE_MANAGEMENT_COMMERCIAL_HUB_BONUS',		  'Amount',			          50),
	('WAREHOUSE_MANAGEMENT_HARBOR_BONUS',						  'YieldType',	          'YIELD_GOLD'),
	('WAREHOUSE_MANAGEMENT_HARBOR_BONUS',						  'Amount',			          50),
	('WAREHOUSE_MANAGEMENT_INDUSTRIAL_ZONE_BONUS',	  'YieldType',	          'YIELD_PRODUCTION'),
	('WAREHOUSE_MANAGEMENT_INDUSTRIAL_ZONE_BONUS',	  'Amount',			          50),
	('AUTO_STEREO_WAREHOUSE_COMMERCIAL_HUB_BONUS',		'YieldType',	          'YIELD_GOLD'),
	('AUTO_STEREO_WAREHOUSE_COMMERCIAL_HUB_BONUS',		'Amount',			          100),
	('AUTO_STEREO_WAREHOUSE_HARBOR_BONUS',						'YieldType',	          'YIELD_GOLD'),
	('AUTO_STEREO_WAREHOUSE_HARBOR_BONUS',						'Amount',			          100),
	('AUTO_STEREO_WAREHOUSE_INDUSTRIAL_ZONE_BONUS',		'YieldType',	          'YIELD_PRODUCTION'),
	('AUTO_STEREO_WAREHOUSE_INDUSTRIAL_ZONE_BONUS',		'Amount',			          100);