-- 造价
update Units set Cost = 150, CostProgressionParam1 = 10, MustPurchase = 0, PrereqTech = 'TECH_CURRENCY' where UnitType = 'UNIT_LEU_TYCOON';
update Units set Cost = 400, CostProgressionParam1 = 20, MustPurchase = 0 where UnitType = 'UNIT_LEU_INVESTOR';

-- 前置建筑
delete from Unit_BuildingPrereqs where Unit = 'UNIT_LEU_TYCOON';
delete from Unit_BuildingPrereqs where Unit = 'UNIT_LEU_INVESTOR';

insert or ignore into Unit_BuildingPrereqs (Unit, PrereqBuilding) select
  'UNIT_LEU_TYCOON', BuildingType
from HD_BuildingTiers where PrereqDistrict = 'DISTRICT_COMMERCIAL_HUB' and Tier = 2;

insert or ignore into Unit_BuildingPrereqs (Unit, PrereqBuilding) select
  'UNIT_LEU_TYCOON', BuildingType
from HD_BuildingTiers where PrereqDistrict = 'DISTRICT_HARBOR' and Tier = 1;

insert or ignore into Unit_BuildingPrereqs (Unit, PrereqBuilding) select
  'UNIT_LEU_INVESTOR', BuildingType
from HD_BuildingTiers where PrereqDistrict = 'DISTRICT_COMMERCIAL_HUB' and Tier = 3;

insert or ignore into Unit_BuildingPrereqs (Unit, PrereqBuilding) select
  'UNIT_LEU_INVESTOR', BuildingType
from HD_BuildingTiers where PrereqDistrict = 'DISTRICT_HARBOR' and Tier = 2;

insert or ignore into Unit_BuildingPrereqs (Unit, PrereqBuilding) values
	('UNIT_LEU_TYCOON',		'BUILDING_RUHR_VALLEY'),
	('UNIT_LEU_INVESTOR',	'BUILDING_RUHR_VALLEY');

-- 单位能力
insert or ignore into Types (Type, Kind) values
	('ABILITY_HD_GOVERNOR_DEFENDER_RIGHT_2_MILITARY_ENGINEERING_ABILITY_2',	    'KIND_ABILITY'),
	('ABILITY_HD_GOVERNOR_MANAGER_LEFT_2_BUILDER_ABILITY',	                    'KIND_ABILITY'),
	('ABILITY_HD_RUHR_VALLEY_TYCOON_ABILITY',	                                  'KIND_ABILITY'),
	('ABILITY_HD_RUHR_VALLEY_INVESTOR_ABILITY',	                                'KIND_ABILITY');

insert or ignore into Tags (Tag, Vocabulary) values
  ('CLASS_TYCOON',  'ABILITY_CLASS');

insert or ignore into TypeTags (Type, Tag) values
  ('ABILITY_HD_GOVERNOR_DEFENDER_RIGHT_2_MILITARY_ENGINEERING_ABILITY_2',			'CLASS_MILITARY_ENGINEERING_UNITS'),
  ('ABILITY_HD_GOVERNOR_MANAGER_LEFT_2_BUILDER_ABILITY',			                'CLASS_BUILDER'),
  ('UNIT_LEU_TYCOON',			                                                    'CLASS_TYCOON'),
  ('ABILITY_HD_RUHR_VALLEY_TYCOON_ABILITY',			                              'CLASS_TYCOON'),
  ('ABILITY_HD_RUHR_VALLEY_INVESTOR_ABILITY',			                            'CLASS_INVESTOR');

insert or ignore into UnitAbilities (UnitAbilityType, Name, Description, Inactive) values
	('ABILITY_HD_GOVERNOR_DEFENDER_RIGHT_2_MILITARY_ENGINEERING_ABILITY_2',
	'LOC_ABILITY_HD_GOVERNOR_DEFENDER_RIGHT_2_MILITARY_ENGINEERING_ABILITY_2_NAME',
	'LOC_ABILITY_HD_GOVERNOR_DEFENDER_RIGHT_2_MILITARY_ENGINEERING_ABILITY_2_DESCRIPTION',
	1),
	('ABILITY_HD_GOVERNOR_MANAGER_LEFT_2_BUILDER_ABILITY',
	'LOC_ABILITY_HD_GOVERNOR_MANAGER_LEFT_2_BUILDER_ABILITY_NAME',
	'LOC_ABILITY_HD_GOVERNOR_MANAGER_LEFT_2_BUILDER_ABILITY_DESCRIPTION',
	1),
	('ABILITY_HD_RUHR_VALLEY_TYCOON_ABILITY',
	'LOC_ABILITY_HD_RUHR_VALLEY_TYCOON_ABILITY_NAME',
	'LOC_ABILITY_HD_RUHR_VALLEY_TYCOON_ABILITY_DESCRIPTION',
	1),
	('ABILITY_HD_RUHR_VALLEY_INVESTOR_ABILITY',
	'LOC_ABILITY_HD_RUHR_VALLEY_INVESTOR_ABILITY_NAME',
	'LOC_ABILITY_HD_RUHR_VALLEY_INVESTOR_ABILITY_DESCRIPTION',
	1);

insert or ignore into UnitAbilityModifiers (UnitAbilityType, ModifierId) values
	('ABILITY_HD_GOVERNOR_DEFENDER_RIGHT_2_MILITARY_ENGINEERING_ABILITY_2', 'HD_GOVERNOR_DEFENDER_RIGHT_2_ALLOW_BUILD_STRATEGIC_INDUSTRY'),
	('ABILITY_HD_GOVERNOR_MANAGER_LEFT_2_BUILDER_ABILITY',						      'HD_GOVERNOR_MANAGER_LEFT_2_ALLOW_BUILD_BONUS_INDUSTRY'),
	('ABILITY_HD_RUHR_VALLEY_TYCOON_ABILITY',						                    'HD_RUHR_VALLEY_ALLOW_TYCOON_BUILD_BONUS_INDUSTRY'),
	('ABILITY_HD_RUHR_VALLEY_TYCOON_ABILITY',						                    'HD_RUHR_VALLEY_ALLOW_TYCOON_BUILD_STRATEGIC_INDUSTRY'),
	('ABILITY_HD_RUHR_VALLEY_INVESTOR_ABILITY',						                  'HD_RUHR_VALLEY_ALLOW_INVESTOR_BUILD_BONUS_CORPORATION'),
	('ABILITY_HD_RUHR_VALLEY_INVESTOR_ABILITY',						                  'HD_RUHR_VALLEY_ALLOW_INVESTOR_BUILD_STRATEGIC_CORPORATION');

insert or ignore into Modifiers (ModifierId, ModifierType) values
  ('HD_GOVERNOR_DEFENDER_RIGHT_2_ALLOW_BUILD_STRATEGIC_INDUSTRY',       'MODIFIER_UNIT_ADJUST_PROPERTY'),
	('HD_GOVERNOR_MANAGER_LEFT_2_ALLOW_BUILD_BONUS_INDUSTRY',             'MODIFIER_UNIT_ADJUST_PROPERTY'),
	('HD_RUHR_VALLEY_ALLOW_TYCOON_BUILD_BONUS_INDUSTRY',                  'MODIFIER_UNIT_ADJUST_PROPERTY'),
	('HD_RUHR_VALLEY_ALLOW_TYCOON_BUILD_STRATEGIC_INDUSTRY',              'MODIFIER_UNIT_ADJUST_PROPERTY'),
	('HD_RUHR_VALLEY_ALLOW_INVESTOR_BUILD_BONUS_CORPORATION',             'MODIFIER_UNIT_ADJUST_PROPERTY'),
	('HD_RUHR_VALLEY_ALLOW_INVESTOR_BUILD_STRATEGIC_CORPORATION',         'MODIFIER_UNIT_ADJUST_PROPERTY');

insert or ignore into ModifierArguments (ModifierId, Name, Value) values
  ('HD_GOVERNOR_DEFENDER_RIGHT_2_ALLOW_BUILD_STRATEGIC_INDUSTRY',       'Key',    'HD_UNIT_CAN_BUILD_STRATEGIC_INDUSTRY'),
	('HD_GOVERNOR_DEFENDER_RIGHT_2_ALLOW_BUILD_STRATEGIC_INDUSTRY',       'Amount', 1),
	('HD_GOVERNOR_MANAGER_LEFT_2_ALLOW_BUILD_BONUS_INDUSTRY',             'Key',    'HD_UNIT_CAN_BUILD_BONUS_INDUSTRY'),
	('HD_GOVERNOR_MANAGER_LEFT_2_ALLOW_BUILD_BONUS_INDUSTRY',             'Amount', 1),
	('HD_RUHR_VALLEY_ALLOW_TYCOON_BUILD_BONUS_INDUSTRY',                  'Key',    'HD_UNIT_CAN_BUILD_BONUS_INDUSTRY'),
	('HD_RUHR_VALLEY_ALLOW_TYCOON_BUILD_BONUS_INDUSTRY',                  'Amount', 1),
	('HD_RUHR_VALLEY_ALLOW_TYCOON_BUILD_STRATEGIC_INDUSTRY',              'Key',    'HD_UNIT_CAN_BUILD_STRATEGIC_INDUSTRY'),
	('HD_RUHR_VALLEY_ALLOW_TYCOON_BUILD_STRATEGIC_INDUSTRY',              'Amount', 1),
	('HD_RUHR_VALLEY_ALLOW_INVESTOR_BUILD_BONUS_CORPORATION',             'Key',    'HD_UNIT_CAN_BUILD_BONUS_CORPORATION'),
	('HD_RUHR_VALLEY_ALLOW_INVESTOR_BUILD_BONUS_CORPORATION',             'Amount', 1),
	('HD_RUHR_VALLEY_ALLOW_INVESTOR_BUILD_STRATEGIC_CORPORATION',         'Key',    'HD_UNIT_CAN_BUILD_STRATEGIC_CORPORATION'),
	('HD_RUHR_VALLEY_ALLOW_INVESTOR_BUILD_STRATEGIC_CORPORATION',         'Amount', 1);