insert or replace into EnglishText (Tag, Text) values
  ("LOC_IMPROVEMENT_CHATEAU_DESCRIPTION_MONOPOLIES",			"+2 [ICON_FOOD] Food, +1 [ICON_Culture] Culture and +1 [ICON_HOUSING] Housing. +1 [ICON_FOOD] Food from every adjacent Bonus resource. +2 [ICON_CULTURE] Culture from every adjacent Luxury resource and Wonder. Provide an extra copy for each adjacent improved Plantation, Farm or Lumber Mill Luxury resource. For each type of adjacent improved Plantation, Farm or Lumber Mill Luxury resource, Château receives its Industry bonus. +1 Appeal to adjacent tiles. Can only be built one per city. Must be placed adjacent to a Bonus or Luxury resource. "),
  
  ("LOC_IMPROVEMENT_INDUSTRY_DESCRIPTION",                "An industry dedicated to a specific Luxury Resource, provides a unique benefit to its city."),
  ("LOC_IMPROVEMENT_CORPORATION_EXPANSION2_DESCRIPTION",  "A company dedicated to a certain type of luxury resource. Allows the City to create [ICON_GreatWork_Product] Product, a new type of Great Work which provides bonus to the City it is stored. Can only be pillaged (never destroyed) by natural disasters. [NEWLINE][NEWLINE]Provides [ICON_TOURISM] Tourism equal to its [ICON_Gold] Gold yield."),
  ("LOC_IMPROVEMENT_LEU_WAREHOUSE_DESCRIPTION",           "+1 [ICON_PRODUCTION] Production to all Industries and Corporations. +1 [ICON_PRODUCTION] Production to all [ICON_TRADEROUTE] Trade Routes. [ICON_GREATWORK_PRODUCT] Products provide +50% [ICON_TOURISM] Tourism in this city. [NEWLINE][NEWLINE]Must be built on a land tile adjacent to a Bonus or Luxury resource. Cannot be built Marsh, Swamp or Geothermal Fissure tiles. Only one may be built in each city, and may not be built adjacent to another Warehouse."),
  ("LOC_IMPROVEMENT_LEU_CONTAINER_PORT_DESCRIPTION",      "+3 [ICON_GOLD] Gold to all Industries and Corporations. +3 [ICON_GOLD] Gold to all [ICON_TRADEROUTE] Trade Routes. [ICON_GREATWORK_PRODUCT] Products provide +50% [ICON_TOURISM] Tourism in this city. [NEWLINE][NEWLINE]Must be built on a Shallow Sea and Lake tile adjacent to land and adjacent to a Bonus or Luxury resource. Only one may be built in each city, and may not be built adjacent to another Container Port."),
  ("LOC_IMPROVEMENT_LEU_STATION_DESCRIPTION",             "Improvement built by Tycoon or Military Engineers. Cannot be built Marsh, Swamp or Geothermal Fissure tiles. Only one may be built in each city, and may not be built adjacent to another Station. Railroads are instantly built on current and adjacent passable land tiles. [NEWLINE][NEWLINE]Improvements of this City provided +50% [ICON_TOURISM] Tourism. +50% [ICON_TOURISM] Tourism to [ICON_GREATWORK_PRODUCT] Products in this City if adjacent to Commercial Hub or Harbor districts. [NEWLINE][NEWLINE]Each type of adjacent Specialized districts or adjacent Aqueduct provide corresponding yield to International [ICON_TradeRoute] Trade Routes from this city. This bonus is doubled if this city is fully [ICON_POWER] Powered.");

insert or replace into LocalizedText (Language, Tag, Text) values
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_CHATEAU_DESCRIPTION_MONOPOLIES",     "+2 [ICON_FOOD] 食物、+1 [ICON_Culture] 文化值、+1 [ICON_HOUSING] 住房。每相邻1个加成资源+1 [ICON_FOOD] 食物，每相邻1个奢侈资源或奇观+2 [ICON_Culture] 文化值。额外提供一份相邻的且已改良的种植园、农场或伐木场奢侈资源。获得每种与城堡庄园相邻且已改良的种植园、农场或伐木场奢侈资源的对应行业效果。为相邻单元格+1魅力。每个城市仅限建造一座，且必须建在加成或奢侈品资源旁。"),
  
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_INDUSTRY_DESCRIPTION",               "致力于一种特定奢侈品资源的行业，能为其所在城市带来独特加成。"),
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_CORPORATION_EXPANSION2_DESCRIPTION", "致力于一种特定奢侈品资源的公司，允许城市开发产品。产品是一种新型的巨作，存有产品的城市将获得一定的加成。无法被自然灾害完全摧毁。[NEWLINE][NEWLINE]获得等同于其 [ICON_Gold] 金币产出的 [ICON_TOURISM] 旅游业绩。"),
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_LEU_STATION_DESCRIPTION",            "由大亨或军事工程师建造，不能建在沼泽或地热裂缝上，一座城市只能拥有一个火车站，火车站不能与另一个火车站相邻。在所在单元格和所有相邻的可通行陆地单元格上自动创建铁路。[NEWLINE][NEWLINE]本城改良提供的 [ICON_TOURISM] 旅游业绩+50%。若相邻商业中心或港口，则分别为本城的 [ICON_GREATWORK_PRODUCT] 产品提供的 [ICON_TOURISM] 旅游业绩+50%。[NEWLINE][NEWLINE]相邻的每种专业化区域或水渠为本城出发的国际 [ICON_TradeRoute] 贸易路线提供对应产出；此城 [ICON_POWER] 供电充足时效果翻倍。"),
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_LEU_WAREHOUSE_NAME",                 "仓库"),
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_LEU_WAREHOUSE_DESCRIPTION",          "所有行业和公司+1 [ICON_PRODUCTION] 生产力。所有 [ICON_TRADEROUTE] 贸易路线+1 [ICON_PRODUCTION] 生产力。本城来自 [ICON_GREATWORK_PRODUCT] 产品的 [ICON_TOURISM] 旅游业绩+50%。[NEWLINE][NEWLINE]必须建在与加成或奢侈资源相邻的单元格上。无法建在沼泽或地热裂缝上。无法建在另一座仓库旁。每个城市仅限建造一座。"),
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_LEU_CONTAINER_PORT_NAME",            "集装箱码头"),
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_LEU_CONTAINER_PORT_DESCRIPTION",     "所有行业和公司+3 [ICON_GOLD] 金币。所有 [ICON_TRADEROUTE] 贸易路线+3 [ICON_GOLD] 金币。本城来自 [ICON_GREATWORK_PRODUCT] 产品的 [ICON_TOURISM] 旅游业绩+50%。[NEWLINE][NEWLINE]必须建在与加成或奢侈资源相邻，且与陆地相邻的浅海或湖泊单元格上。无法建在另一座集装箱码头旁。每个城市仅限建造一座。"),
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_LEU_TRANSNATIONAL_NAME",             "跨国公司"),
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_LEU_TRANSNATIONAL_DESCRIPTION",      "只能建造在有奢侈品资源或战略资源的无主单元格上。建成后，将占领该单元格，获得该资源，并直接将其产量提供给[ICON_CAPITAL]首都。如果其所在的单元格被掠夺，您将失去该单元格并移除该改良设施。"),
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_LEU_TRANSNATIONAL_SEA_NAME",         "离岸油轮"),
  ("zh_Hans_CN",  "LOC_IMPROVEMENT_LEU_TRANSNATIONAL_SEA_DESCRIPTION",  "只能建造在有奢侈品资源或战略资源的无主水域单元格上。将占领该单元格，获得该资源，并直接将其产量提供给[ICON_CAPITAL]首都。如果其所在的单元格被掠夺，您将失去该单元格并移除该改良设施。");
  
 