insert or replace into EnglishText (Tag, Text) values
  -- 威尼斯军械库
  ("LOC_BUILDING_VENETIAN_ARSENAL_CORP_DESCRIPTION",                "Grants a Tycoon. {LOC_BUILDING_VENETIAN_ARSENAL_DESCRIPTION}"),
  -- 鲁尔山谷
  ("LOC_BUILDING_RUHR_VALLEY_CORP_DESCRIPTION",                     "Provides 6 [ICON_RESOURCE_COAL] Coal per turn. Tycoon can build Industry on Bonus or Strategic Resources. Investor can build Corporation on Bonus or Strategic Resources. Corporation of Bonus Resources provides +5% [ICON_PRODUCTION] Production to its city. Corporation of Strategic Resources provides +5% [ICON_Science] Science. Each Industry and Corporation in your empire provide +5% accumulation rate for [ICON_GREATENGINEER] Great Engineer Points. [NEWLINE][NEWLINE]Must be built adjacent to River."),
  -- 巴拿马运河
  ("LOC_BUILDING_PANAMA_CANAL_DESCRIPTION",                         "Grants 1 free [ICON_GreatMerchant] Great Merchant. Canal districts across your empire provide +10% [ICON_GREATMERCHANT] Great Merchant points you generate. [ICON_Greatwork_Product] Product in cities with Canal districts provide +50% [ICON_Tourism] Tourism. Each type of Specialized districts or Aqueduct adjacent to Canal district or Panama Canal in this city provide corresponding yield to International [ICON_TradeRoute] Trade Routes from this city.[NEWLINE][NEWLINE]Upon completion 1 or 2 adjacent Canal districts are automatically constructed. The Canal wonder tile can now be crossed by naval units. Must be built on a flat land tile where there are two adjacent tiles directly across the build tile from one another that meet the following criteria: one adjacent tile must be able to legally hold a Canal district connecting into the Panama Canal construction tile; the other must be either a city, a Lake/Coast tile, or be another tile that can hold a connecting Canal."),
  -- 帝国大厦
  ("LOC_WON_CL_EMPIRE_STATES_DESCRIPTION",                          "Wonders in this City provide +6 [ICON_GOLD] Gold and +200% [ICON_Tourism] Tourism. Cities with an established [ICON_Governor] Governor receive the following buff: for each Promotion the Governor has earned (including the first), [ICON_Greatwork_Product] Products provide +25% [ICON_Tourism] Tourism, and the City yield +5% [ICON_Gold] Gold.[NEWLINE]Must be built on flat land adjacent to the City Center."),
  -- 金融中心
  ("LOC_NAT_WON_CL_FINANCE_CORP_DESCRIPTION",                       "Can only be built once in your empire. To unlock: Maintain 8 [ICON_TradeRoute] Trade Routes. Must be built on land tile adjacent to a Corporation on Luxury Resource. [NEWLINE][NEWLINE]Corporations on Luxury Resource provide +20% [ICON_Gold] Gold to its city. In Cities with a Exhibition Center, Corporations provide +200% [ICON_TOURISM] Tourism; [ICON_GreatWork_Product] Products provide 1.5 times of all yields and +50% [ICON_TOURISM] Tourism. Great People patronage cost -50% [ICON_Gold] Gold."),
  ("LOC_NAT_WON_CL_FINANCE_CORP_DESCRIPTION_INTERNAL",              "Can only be built once in your empire. [COLOR:Red]To unlock: Maintain 8 [ICON_TradeRoute] Trade Routes.[ENDCOLOR] Must be built on land tile adjacent to a Corporation on Luxury Resource. [NEWLINE][NEWLINE]Corporations on Luxury Resource provide +20% [ICON_Gold] Gold to its city. In Cities with a Exhibition Center, Corporations provide +200% [ICON_TOURISM] Tourism; [ICON_GreatWork_Product] Products provide 1.5 times of all yields and +50% [ICON_TOURISM] Tourism. Great People patronage cost -50% [ICON_Gold] Gold.");

insert or replace into LocalizedText (Language, Tag, Text) values
  -- 威尼斯军械库
  ("zh_Hans_CN",  "LOC_BUILDING_VENETIAN_ARSENAL_CORP_DESCRIPTION",                "获得1个大亨。{LOC_BUILDING_VENETIAN_ARSENAL_DESCRIPTION}"),
  -- 鲁尔山谷
  ("zh_Hans_CN",  "LOC_BUILDING_RUHR_VALLEY_CORP_DESCRIPTION",                     "每回合提供6点 [ICON_RESOURCE_COAL] 煤。大亨可以在加成资源或战略资源上创立行业，投资人可以在加成资源或战略资源上创立公司。加成资源公司为所在城市+5% [ICON_PRODUCTION] 生产力，战略资源公司为所在城市+5% [ICON_Science] 科技值。境内每个行业或公司使玩家的 [ICON_GREATENGINEER] 大工程师点数积累速度+5%。[NEWLINE][NEWLINE]必须沿河而建。"),
  -- 巴拿马运河
  ("zh_Hans_CN",  "LOC_BUILDING_PANAMA_CANAL_DESCRIPTION",                         "建成时市中心出现一位 [ICON_GreatMerchant] 大商人。境内的每个运河使玩家的 [ICON_GREATMERCHANT] 大商人点数积累速度+10%。拥有运河的城市来自 [ICON_GreatWork_Product] 产品的 [ICON_Tourism] 旅游业绩+50%。本城的每个运河（包括巴拿马运河）相邻的每种专业化区域或水渠为本城出发的国际 [ICON_TradeRoute] 贸易路线提供对应产出。[NEWLINE][NEWLINE]开始修建巴拿马运河时，将在满足条件的相邻单元格自动开始建造1或2个运河，完成巴拿马运河的同时运河也将完成。建成的巴拿马运河将同样被视为运河。[NEWLINE]将巴拿马运河视为水域单元格时，必须有两个相邻巴拿马运河的且关于其对称的单元格满足：两个单元格均可以修建运河；或是一个单元格可以修建运河，一个单元格是城市/水域。如想使用巴拿马运河连接两座城市，那么这两座城市必须有至少一座相邻水域单元格或已经被运河连接至水域单元格。[NEWLINE][NEWLINE]必须修建在平坦地形单元格之上。"),
  -- 帝国大厦
  ("zh_Hans_CN",  "LOC_WON_CL_EMPIRE_STATES_DESCRIPTION",                          "该城市的每座奇观+6 [ICON_GOLD] 金币和且奇观的 [ICON_Tourism] 旅游业绩+200%。[ICON_Governor] 总督在城市中就职后，每次升级（包括首次升级）都将提供 +5% [ICON_Gold] 金币，并使来自 [ICON_GreatWork_Product] 产品的 [ICON_Tourism] 旅游业绩+25%。[NEWLINE]必须建在靠近市中心的平坦地形上。"),
  -- 金融中心
  ("zh_Hans_CN",  "LOC_NAT_WON_CL_FINANCE_CORP_DESCRIPTION",                       "国家境内只能建造一座。解锁条件：经营8条贸易路线。必须建在与奢侈资源公司相邻的陆地上。[NEWLINE][NEWLINE][ICON_GreatPerson] 伟人赞助消耗的 [ICON_Gold] 金币减少50%。公司为所在城市+10% [ICON_Gold] 金币。在建有会展中心的城市中，公司产出的 [ICON_Tourism] 旅游业绩+200%，[ICON_GreatWork_Product] 产品获得1.5倍产出和+100% [ICON_Tourism] 旅游业绩。"),
  ("zh_Hans_CN",  "LOC_NAT_WON_CL_FINANCE_CORP_DESCRIPTION_INTERNAL",              "国家境内只能建造一座。[COLOR:Red]解锁条件：经营8条贸易路线。[ENDCOLOR]必须建在与奢侈资源公司相邻的陆地上。[NEWLINE][NEWLINE][ICON_GreatPerson] 伟人赞助消耗的 [ICON_Gold] 金币减少50%。公司为所在城市+10% [ICON_Gold] 金币。在建有会展中心的城市中，公司产出的 [ICON_Tourism] 旅游业绩+200%，[ICON_GreatWork_Product] 产品获得1.5倍产出和+100% [ICON_Tourism] 旅游业绩。");