--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText (Tag, Text) values
	("LOC_GAMEMODE_MONOPOLIES_NAME",                                  "Industries and Corporations Mode"),
	("LOC_GAMEMODE_MONOPOLIES_DESCRIPTION",                           "[COLOR_Civ6LightBlue]Welcome to ""Harmony in Diversity"": Industries and Corporations Mode, We have overhaul and redesigned the benefits of Industries, Corporations and Products. Please read the in-game civilopeida about the details.[ENDCOLOR][NEWLINE]Control, improve, and expand upon your Luxury resources! The Industries and Corporations mode enables you to build profitable Industries around Luxury resources, found Corporations to further their development, and manufacture unique Products to secure your place in business history."),
	("LOC_TRAIT_CIVILIZATION_AMAZON_DESCRIPTION_MONOPOLIES",          "Grant a Bandeirante after establishing [ICON_CAPITAL] Capital city. All districts (except city centers) will not remove Rainforest. Rainforest tiles provide a standard adjacency bonus for specialty districts, and grant +1 Appeal to adjacent tiles. When establishing an industry for the first time of each resource, grant a Bandeirante and all Bandeirantes receive +1 collection times. When you build Industry or Corporation on Rainforest tiles, immediately activate the corresponding bonus of all its usages."),
	("LOC_UNIT_HD_BANDEIRANTES_DESCRIPTION_MONOPOLIES",               "Brazilian unique Recon unit, but cannot be trained, purchased or upgraded to a more advanced unit. Its [ICON_STRENGTH] Combat Strength increases according to your era. It automatically creates roads when passing through Woods, Rainforest, Marsh{LOC_OR_SWAMP_NAME}. It can collect resources on unowned rainforest tiles for 4 times. For every two of the same resource collected, the improved Resources on rainforest tiles in your cities gain the yields of that resource."),
	("LOC_IMPROVEMENT_CHATEAU_DESCRIPTION_MONOPOLIES",			      		"+2 [ICON_FOOD] Food, +1 [ICON_Culture] Culture and +1 [ICON_HOUSING] Housing. +1 [ICON_FOOD] Food and [ICON_PRODUCTION] Production from every adjacent district. +2 [ICON_CULTURE] Culture from every adjacent Wonder. +1 [ICON_CULTURE] Culture from every Château in your empire. +1 Appeal to adjacent tiles. [NEWLINE]Upon construction, you may choose an improved Resource in this city of Crops, Fruit, Brewing or Beverage Usage as the ""[COLOR:Green]Production Resource[ENDCOLOR]"" for this Château. When the city has built a Medieval or later Wonder, you may choose an improved Resource in this city of Cloth, Art, Decoration or Ornamental Usage as the ""[COLOR:219,112,147,255]Entertainment Resource[ENDCOLOR]"" for this Château. The city receives the industrial bonuses of the selected resource; if a luxury resource is chosen, an additional copy of that resource is provided. [NEWLINE]Can only be built one per city.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText (Language, Tag, Text) values
	("zh_Hans_CN",  "LOC_GAMEMODE_MONOPOLIES_NAME",                                  "行业与公司模式"),
	("zh_Hans_CN",  "LOC_GAMEMODE_MONOPOLIES_DESCRIPTION",                           "[COLOR_Civ6LightBlue]欢迎来到“和而不同”行业与公司模式，我们对行业、公司、产品的效果进行了全面的重制，请查阅内置百科了解详情。[ENDCOLOR][NEWLINE]控制、改良您的奢侈品资源，并在此之上进行拓展！在“行业与公司”模式中，您可以围绕奢侈品资源建立利润丰硕的行业、创建公司进行深度开发，并生产特色产品，确立您在商业历史中的显著地位。"),
	("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_AMAZON_DESCRIPTION_MONOPOLIES", 				 "建立 [ICON_CAPITAL] 首都后获得一位旗手。除市中心外的区域不移除雨林。雨林单元格为专业化区域提供标准相邻加成，并为相邻的单元格提供+1魅力。首次建立某种资源的行业时，获得一名旗手，且所有旗手+1收集次数。建造在雨林上的行业或公司直接激活所有用途所对应的加成效果。"),
	("zh_Hans_CN",  "LOC_UNIT_HD_BANDEIRANTES_DESCRIPTION_MONOPOLIES",               "巴西特色侦察单位，无法升级成高级单位，无法在城市中建造或购买该单位。[ICON_STRENGTH] 战斗力随你所处的时代提升。经过森林、雨林或沼泽时自动创建道路。可以收集4次无主雨林单元格上的资源，每收集两个同种资源，境内改良的雨林资源获得该资源的产出。"),
	("zh_Hans_CN",  "LOC_IMPROVEMENT_CHATEAU_DESCRIPTION_MONOPOLIES",                "+2 [ICON_FOOD] 食物、+1 [ICON_HOUSING] 住房。每相邻1个区域+1 [ICON_FOOD] 食物和 [ICON_PRODUCTION] 生产力，每相邻1个奇观+2 [ICON_Culture] 文化值。境内每有一座城堡庄园+1 [ICON_CULTURE] 文化值。为相邻单元格+1魅力。[NEWLINE]建成后，可以从本城改良的庄稼、水果、酿造或饮料资源中选择一个作为该城堡庄园的“[COLOR:Green]生产资源[ENDCOLOR]”；当城市拥有一座中世纪或以后的奇观后，可以从本城改良的服装、艺术、饰品或花木资源中选择一个作为该城堡庄园的“[COLOR:219,112,147,255]娱乐资源[ENDCOLOR]”。该城市获得被选中的资源的行业效果；若选中的为奢侈资源，则额外提供一份该资源。[NEWLINE]每个城市仅限建造一座。");